namespace Trade.It
{
    partial class Form1
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.MenuStrip mainMenuStrip;
        private System.Windows.Forms.ToolStripMenuItem portfolioDefinitionMenuItem;
        private System.Windows.Forms.ToolStripMenuItem portfolioManagementMenuItem;
        private System.Windows.Forms.ToolStripMenuItem settingsMenuItem;
        private System.Windows.Forms.SplitContainer mainSplitContainer;
        private System.Windows.Forms.TabControl controlTabControl;
        private System.Windows.Forms.TabPage stocksTabPage;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.TabPage tabPage3;
        private System.Windows.Forms.ComboBox portfolioComboBox;
        private System.Windows.Forms.Label portfolioLabel;
        private System.Windows.Forms.DataGridView stocksDataGridView;
        private System.Windows.Forms.FlowLayoutPanel stocksBottomPanel;
        private System.Windows.Forms.Button navigationButton;
        private System.Windows.Forms.Button newPortfolioButton;
        private System.Windows.Forms.Button refreshButton;
        private System.Windows.Forms.Button deleteButton;
        private System.Windows.Forms.CheckBox selectAllCheckBox;
        private System.Windows.Forms.CheckBox selectNoneCheckBox;
        private System.Windows.Forms.Label speedLabel;
        private System.Windows.Forms.TextBox navigationSpeedTextBox;
        private System.Windows.Forms.Panel chartPanel;
        private System.Windows.Forms.Panel chartToolbarPanel;
        private System.Windows.Forms.ComboBox chartTypeComboBox;
        private System.Windows.Forms.Button gridButton;
        private System.Windows.Forms.Button crossButton;
        private System.Windows.Forms.Button zoomInButton;
        private System.Windows.Forms.Button zoomOutButton;
        private System.Windows.Forms.Button resetChartButton;
        private System.Windows.Forms.Button hideChartButton;
        private System.Windows.Forms.Button hideToolsButton;
        private System.Windows.Forms.Button printChartButton;
        private System.Windows.Forms.Button snapshotChartButton;
        private System.Windows.Forms.Button fullScreenChartButton;
        private System.Windows.Forms.Button closeAllChartsButton;
        private System.Windows.Forms.TabControl chartTabControl;
        private System.Windows.Forms.TabPage chartTabPage;
        private System.Windows.Forms.Panel chartInfoPanel;
        private System.Windows.Forms.Label chartInfoLabel;
        private System.Windows.Forms.Label chartPlaceholderLabel;
        private System.Windows.Forms.DataGridViewTextBoxColumn rowColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn symbolColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn lastTradeColumn;
        private System.Windows.Forms.DataGridViewCheckBoxColumn selectColumn;
        private System.Windows.Forms.Button refreshButtonPortfolio;
        private System.Windows.Forms.GroupBox tradingStatusGroup;
        private System.Windows.Forms.RadioButton statusAllRadio;
        private System.Windows.Forms.RadioButton statusPositiveRadio;
        private System.Windows.Forms.RadioButton statusNegativeRadio;
        private System.Windows.Forms.GroupBox nameFilterGroup;
        private System.Windows.Forms.GroupBox volumeRatioGroup;
        private System.Windows.Forms.TextBox volumeRatioTextBox;
        private System.Windows.Forms.ComboBox volumeRatioOperatorComboBox;
        private System.Windows.Forms.GroupBox pastDaysGroup;
        private System.Windows.Forms.TextBox pastDaysTextBox;
        private System.Windows.Forms.ComboBox pastDaysStatusComboBox;
        private System.Windows.Forms.GroupBox comparisonGroup;
        private System.Windows.Forms.ComboBox comparisonFirstComboBox;
        private System.Windows.Forms.ComboBox comparisonOperatorComboBox;
        private System.Windows.Forms.ComboBox comparisonSecondComboBox;
        private System.Windows.Forms.GroupBox comparisonGroup6;
        private System.Windows.Forms.ComboBox comparisonFirstComboBox6;
        private System.Windows.Forms.ComboBox comparisonOperatorComboBox6;
        private System.Windows.Forms.ComboBox comparisonSecondComboBox6;
        private System.Windows.Forms.TextBox comparisonFirstTextBox6;
        private System.Windows.Forms.TextBox comparisonSecondTextBox6;
        private System.Windows.Forms.Label label5_6;
        private System.Windows.Forms.Label label6_6;
        private System.Windows.Forms.Label label7_6;
        private System.Windows.Forms.Label label8_6;
        private System.Windows.Forms.GroupBox comparisonGroup7;
        private System.Windows.Forms.ComboBox comparisonFirstComboBox7;
        private System.Windows.Forms.ComboBox comparisonOperatorComboBox7;
        private System.Windows.Forms.ComboBox comparisonSecondComboBox7;
        private System.Windows.Forms.TextBox comparisonFirstTextBox7;
        private System.Windows.Forms.TextBox comparisonSecondTextBox7;
        private System.Windows.Forms.Label label5_7;
        private System.Windows.Forms.Label label6_7;
        private System.Windows.Forms.Label label7_7;
        private System.Windows.Forms.Label label8_7;
        private System.Windows.Forms.GroupBox comparisonGroup8;
        private System.Windows.Forms.ComboBox comparisonFirstComboBox8;
        private System.Windows.Forms.ComboBox comparisonOperatorComboBox8;
        private System.Windows.Forms.ComboBox comparisonSecondComboBox8;
        private System.Windows.Forms.TextBox comparisonFirstTextBox8;
        private System.Windows.Forms.TextBox comparisonSecondTextBox8;
        private System.Windows.Forms.Label label5_8;
        private System.Windows.Forms.Label label6_8;
        private System.Windows.Forms.Label label7_8;
        private System.Windows.Forms.Label label8_8;
        private System.Windows.Forms.GroupBox identifierMainGroup;
        private System.Windows.Forms.TableLayoutPanel identifierLayout;
        private System.Windows.Forms.Label identifierSymbolLabel;
        private System.Windows.Forms.TextBox identifierSymbolTextBox;
        private System.Windows.Forms.Label identifierNameLabel;
        private System.Windows.Forms.TextBox identifierNameTextBox;
        private System.Windows.Forms.Label identifierTsetmcLabel;
        private System.Windows.Forms.TextBox identifierTsetmcTextBox;
        private System.Windows.Forms.Label identifierMarketLabel;
        private System.Windows.Forms.ComboBox identifierMarketComboBox;
        private System.Windows.Forms.Label identifierGroupLabel;
        private System.Windows.Forms.TextBox identifierGroupTextBox;
        private System.Windows.Forms.Label identifierDescriptionLabel;
        private System.Windows.Forms.TextBox identifierDescriptionTextBox;
        private System.Windows.Forms.ComboBox nameComboBox;
        private System.Windows.Forms.TextBox nameTextBox;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.TextBox comparisonSecondTextBox;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.TextBox comparisonFirstTextBox;
        private System.Windows.Forms.Label label5;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            mainMenuStrip = new MenuStrip();
            portfolioDefinitionMenuItem = new ToolStripMenuItem();
            portfolioManagementMenuItem = new ToolStripMenuItem();
            settingsMenuItem = new ToolStripMenuItem();
            mainSplitContainer = new SplitContainer();
            chartPanel = new Panel();
            chartTabControl = new TabControl();
            chartTabPage = new TabPage();
            chartInfoPanel = new Panel();
            chartInfoLabel = new Label();
            chartPlaceholderLabel = new Label();
            chartToolbarPanel = new Panel();
            chartTypeComboBox = new ComboBox();
            gridButton = new Button();
            crossButton = new Button();
            zoomInButton = new Button();
            zoomOutButton = new Button();
            resetChartButton = new Button();
            hideChartButton = new Button();
            hideToolsButton = new Button();
            printChartButton = new Button();
            snapshotChartButton = new Button();
            fullScreenChartButton = new Button();
            closeAllChartsButton = new Button();
            controlTabControl = new TabControl();
            stocksTabPage = new TabPage();
            refreshButtonPortfolio = new Button();
            stocksDataGridView = new DataGridView();
            rowColumn = new DataGridViewTextBoxColumn();
            symbolColumn = new DataGridViewTextBoxColumn();
            lastTradeColumn = new DataGridViewTextBoxColumn();
            selectColumn = new DataGridViewCheckBoxColumn();
            stocksBottomPanel = new FlowLayoutPanel();
            refreshButton = new Button();
            navigationSpeedTextBox = new TextBox();
            speedLabel = new Label();
            navigationButton = new Button();
            newPortfolioButton = new Button();
            deleteButton = new Button();
            selectNoneCheckBox = new CheckBox();
            selectAllCheckBox = new CheckBox();
            portfolioComboBox = new ComboBox();
            portfolioLabel = new Label();
            tabPage2 = new TabPage();
            comparisonGroup = new GroupBox();
            comparisonFirstComboBox = new ComboBox();
            comparisonOperatorComboBox = new ComboBox();
            comparisonSecondComboBox = new ComboBox();
            pastDaysGroup = new GroupBox();
            pastDaysStatusComboBox = new ComboBox();
            pastDaysTextBox = new TextBox();
            volumeRatioGroup = new GroupBox();
            volumeRatioOperatorComboBox = new ComboBox();
            volumeRatioTextBox = new TextBox();
            nameFilterGroup = new GroupBox();
            tradingStatusGroup = new GroupBox();
            statusAllRadio = new RadioButton();
            statusPositiveRadio = new RadioButton();
            statusNegativeRadio = new RadioButton();
            comparisonGroup6 = new GroupBox();
            comparisonFirstComboBox6 = new ComboBox();
            comparisonOperatorComboBox6 = new ComboBox();
            comparisonSecondComboBox6 = new ComboBox();
            comparisonFirstTextBox6 = new TextBox();
            comparisonSecondTextBox6 = new TextBox();
            label5_6 = new Label(); label6_6 = new Label(); label7_6 = new Label(); label8_6 = new Label();
            comparisonGroup7 = new GroupBox();
            comparisonFirstComboBox7 = new ComboBox(); comparisonOperatorComboBox7 = new ComboBox(); comparisonSecondComboBox7 = new ComboBox(); comparisonFirstTextBox7 = new TextBox(); comparisonSecondTextBox7 = new TextBox(); label5_7 = new Label(); label6_7 = new Label(); label7_7 = new Label(); label8_7 = new Label();
            comparisonGroup8 = new GroupBox();
            comparisonFirstComboBox8 = new ComboBox(); comparisonOperatorComboBox8 = new ComboBox(); comparisonSecondComboBox8 = new ComboBox(); comparisonFirstTextBox8 = new TextBox(); comparisonSecondTextBox8 = new TextBox(); label5_8 = new Label(); label6_8 = new Label(); label7_8 = new Label(); label8_8 = new Label();
            tabPage3 = new TabPage();
            identifierMainGroup = new GroupBox();
            identifierLayout = new TableLayoutPanel();
            identifierSymbolLabel = new Label(); identifierSymbolTextBox = new TextBox(); identifierNameLabel = new Label(); identifierNameTextBox = new TextBox(); identifierTsetmcLabel = new Label(); identifierTsetmcTextBox = new TextBox(); identifierMarketLabel = new Label(); identifierMarketComboBox = new ComboBox(); identifierGroupLabel = new Label(); identifierGroupTextBox = new TextBox(); identifierDescriptionLabel = new Label(); identifierDescriptionTextBox = new TextBox();
            nameComboBox = new ComboBox(); nameTextBox = new TextBox(); textBox1 = new TextBox(); label1 = new Label(); label2 = new Label(); label3 = new Label(); label4 = new Label(); label5 = new Label(); comparisonFirstTextBox = new TextBox(); label6 = new Label(); label7 = new Label(); label8 = new Label(); comparisonSecondTextBox = new TextBox();
            mainMenuStrip.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)mainSplitContainer).BeginInit(); mainSplitContainer.Panel1.SuspendLayout(); mainSplitContainer.Panel2.SuspendLayout(); mainSplitContainer.SuspendLayout();
            chartPanel.SuspendLayout(); chartTabControl.SuspendLayout(); chartTabPage.SuspendLayout(); chartInfoPanel.SuspendLayout(); chartToolbarPanel.SuspendLayout(); controlTabControl.SuspendLayout(); stocksTabPage.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)stocksDataGridView).BeginInit(); stocksBottomPanel.SuspendLayout(); tabPage2.SuspendLayout(); comparisonGroup.SuspendLayout(); pastDaysGroup.SuspendLayout(); volumeRatioGroup.SuspendLayout(); nameFilterGroup.SuspendLayout(); tradingStatusGroup.SuspendLayout(); comparisonGroup6.SuspendLayout(); comparisonGroup7.SuspendLayout(); comparisonGroup8.SuspendLayout(); tabPage3.SuspendLayout(); identifierMainGroup.SuspendLayout(); identifierLayout.SuspendLayout(); SuspendLayout();
            mainMenuStrip.ImageScalingSize = new Size(20, 20); mainMenuStrip.Items.AddRange(new ToolStripItem[] { portfolioDefinitionMenuItem, portfolioManagementMenuItem, settingsMenuItem }); mainMenuStrip.Location = new Point(0, 0); mainMenuStrip.Name = "mainMenuStrip"; mainMenuStrip.RightToLeft = RightToLeft.No; mainMenuStrip.Size = new Size(1288, 36); mainMenuStrip.TabIndex = 0;
            portfolioDefinitionMenuItem.Name = "portfolioDefinitionMenuItem"; portfolioDefinitionMenuItem.Size = new Size(121, 32); portfolioDefinitionMenuItem.Text = "تعریف سبد";
            portfolioManagementMenuItem.Name = "portfolioManagementMenuItem"; portfolioManagementMenuItem.Size = new Size(129, 32); portfolioManagementMenuItem.Text = "مدیریت سبد";
            settingsMenuItem.Name = "settingsMenuItem"; settingsMenuItem.Size = new Size(99, 32); settingsMenuItem.Text = "تنظیمات";
            mainSplitContainer.Dock = DockStyle.Fill; mainSplitContainer.Location = new Point(0, 36); mainSplitContainer.Name = "mainSplitContainer"; mainSplitContainer.Panel1.Controls.Add(chartPanel); mainSplitContainer.Panel1MinSize = 500; mainSplitContainer.Panel2.Controls.Add(controlTabControl); mainSplitContainer.Panel2MinSize = 300; mainSplitContainer.Size = new Size(1288, 744); mainSplitContainer.SplitterDistance = 869; mainSplitContainer.TabIndex = 1;
            chartPanel.BorderStyle = BorderStyle.FixedSingle; chartPanel.Controls.Add(chartTabControl); chartPanel.Controls.Add(chartToolbarPanel); chartPanel.Dock = DockStyle.Fill; chartPanel.Location = new Point(0, 0); chartPanel.Name = "chartPanel"; chartPanel.Size = new Size(869, 744); chartPanel.TabIndex = 0;
            chartTabControl.Controls.Add(chartTabPage); chartTabControl.Dock = DockStyle.Fill; chartTabControl.Location = new Point(0, 51); chartTabControl.Name = "chartTabControl"; chartTabControl.SelectedIndex = 0; chartTabControl.Size = new Size(867, 691); chartTabControl.TabIndex = 0;
            chartTabPage.Controls.Add(chartInfoPanel); chartTabPage.Controls.Add(chartPlaceholderLabel); chartTabPage.Location = new Point(4, 34); chartTabPage.Name = "chartTabPage"; chartTabPage.Padding = new Padding(3); chartTabPage.Size = new Size(859, 653); chartTabPage.TabIndex = 0; chartTabPage.Text = "نماد";
            chartInfoPanel.BackColor = SystemColors.Control; chartInfoPanel.Controls.Add(chartInfoLabel); chartInfoPanel.Dock = DockStyle.Top; chartInfoPanel.Location = new Point(3, 3); chartInfoPanel.Name = "chartInfoPanel"; chartInfoPanel.Size = new Size(853, 30); chartInfoPanel.TabIndex = 0;
            chartInfoLabel.Dock = DockStyle.Fill; chartInfoLabel.Location = new Point(0, 0); chartInfoLabel.Name = "chartInfoLabel"; chartInfoLabel.Padding = new Padding(8, 0, 0, 0); chartInfoLabel.Size = new Size(853, 30); chartInfoLabel.TabIndex = 0; chartInfoLabel.Text = "O: —    H: —    L: —    C: —    V: — تاریخ/زمان : —    "; chartInfoLabel.TextAlign = ContentAlignment.MiddleLeft;
            chartPlaceholderLabel.Dock = DockStyle.Fill; chartPlaceholderLabel.Font = new Font("Segoe UI", 14F); chartPlaceholderLabel.Location = new Point(3, 3); chartPlaceholderLabel.Name = "chartPlaceholderLabel"; chartPlaceholderLabel.Size = new Size(853, 647); chartPlaceholderLabel.TabIndex = 1; chartPlaceholderLabel.Text = "ناحیه رسم چارت"; chartPlaceholderLabel.TextAlign = ContentAlignment.MiddleCenter;
            chartToolbarPanel.BorderStyle = BorderStyle.FixedSingle; chartToolbarPanel.Controls.Add(chartTypeComboBox); chartToolbarPanel.Controls.Add(gridButton); chartToolbarPanel.Controls.Add(crossButton); chartToolbarPanel.Controls.Add(zoomInButton); chartToolbarPanel.Controls.Add(zoomOutButton); chartToolbarPanel.Controls.Add(resetChartButton); chartToolbarPanel.Controls.Add(hideChartButton); chartToolbarPanel.Controls.Add(hideToolsButton); chartToolbarPanel.Controls.Add(printChartButton); chartToolbarPanel.Controls.Add(snapshotChartButton); chartToolbarPanel.Controls.Add(fullScreenChartButton); chartToolbarPanel.Controls.Add(closeAllChartsButton); chartToolbarPanel.Dock = DockStyle.Top; chartToolbarPanel.Location = new Point(0, 0); chartToolbarPanel.Name = "chartToolbarPanel"; chartToolbarPanel.Padding = new Padding(6, 5, 6, 5); chartToolbarPanel.Size = new Size(867, 51); chartToolbarPanel.TabIndex = 1;
            chartTypeComboBox.DropDownStyle = ComboBoxStyle.DropDownList; chartTypeComboBox.Items.AddRange(new object[] { "شمعی", "خطی", "میله ای" }); chartTypeComboBox.Location = new Point(6, 8); chartTypeComboBox.Name = "chartTypeComboBox"; chartTypeComboBox.Size = new Size(82, 33); chartTypeComboBox.TabIndex = 0;
            gridButton.Location = new Point(91, 7); gridButton.Name = "gridButton"; gridButton.Size = new Size(50, 34); gridButton.TabIndex = 1; gridButton.Text = "گرید";
            crossButton.Location = new Point(142, 7); crossButton.Name = "crossButton"; crossButton.Size = new Size(56, 34); crossButton.TabIndex = 2; crossButton.Text = "Cross";
            zoomInButton.Location = new Point(199, 7); zoomInButton.Name = "zoomInButton"; zoomInButton.Size = new Size(48, 34); zoomInButton.TabIndex = 3; zoomInButton.Text = "+";
            zoomOutButton.Location = new Point(248, 7); zoomOutButton.Name = "zoomOutButton"; zoomOutButton.Size = new Size(48, 34); zoomOutButton.TabIndex = 4; zoomOutButton.Text = "−";
            resetChartButton.Location = new Point(297, 7); resetChartButton.Name = "resetChartButton"; resetChartButton.Size = new Size(62, 34); resetChartButton.TabIndex = 5; resetChartButton.Text = "Reset";
            hideChartButton.Location = new Point(364, 7); hideChartButton.Name = "hideChartButton"; hideChartButton.Size = new Size(106, 34); hideChartButton.TabIndex = 6; hideChartButton.Text = "مخفی چارت";
            hideToolsButton.Location = new Point(475, 7); hideToolsButton.Name = "hideToolsButton"; hideToolsButton.Size = new Size(96, 34); hideToolsButton.TabIndex = 7; hideToolsButton.Text = "مخفی ابزار";
            printChartButton.Location = new Point(576, 7); printChartButton.Name = "printChartButton"; printChartButton.Size = new Size(56, 34); printChartButton.TabIndex = 8; printChartButton.Text = "چاپ";
            snapshotChartButton.Location = new Point(637, 7); snapshotChartButton.Name = "snapshotChartButton"; snapshotChartButton.Size = new Size(56, 34); snapshotChartButton.TabIndex = 9; snapshotChartButton.Text = "عکس";
            fullScreenChartButton.Location = new Point(698, 7); fullScreenChartButton.Name = "fullScreenChartButton"; fullScreenChartButton.Size = new Size(75, 34); fullScreenChartButton.TabIndex = 10; fullScreenChartButton.Text = "تمام‌صفحه";
            closeAllChartsButton.Location = new Point(779, 7); closeAllChartsButton.Name = "closeAllChartsButton"; closeAllChartsButton.Size = new Size(80, 34); closeAllChartsButton.TabIndex = 11; closeAllChartsButton.Text = "بستن همه چارت ها";
            controlTabControl.Controls.Add(stocksTabPage); controlTabControl.Controls.Add(tabPage2); controlTabControl.Controls.Add(tabPage3); controlTabControl.Dock = DockStyle.Fill; controlTabControl.Location = new Point(0, 0); controlTabControl.Name = "controlTabControl"; controlTabControl.RightToLeft = RightToLeft.Yes; controlTabControl.RightToLeftLayout = true; controlTabControl.SelectedIndex = 0; controlTabControl.Size = new Size(415, 744); controlTabControl.TabIndex = 0;
            stocksTabPage.Controls.Add(refreshButtonPortfolio); stocksTabPage.Controls.Add(stocksDataGridView); stocksTabPage.Controls.Add(stocksBottomPanel); stocksTabPage.Controls.Add(portfolioComboBox); stocksTabPage.Controls.Add(portfolioLabel); stocksTabPage.Location = new Point(4, 34); stocksTabPage.Name = "stocksTabPage"; stocksTabPage.Padding = new Padding(8); stocksTabPage.Size = new Size(407, 706); stocksTabPage.TabIndex = 0; stocksTabPage.Text = "سهام";
            refreshButtonPortfolio.Location = new Point(15, 7); refreshButtonPortfolio.Name = "refreshButtonPortfolio"; refreshButtonPortfolio.Size = new Size(91, 34); refreshButtonPortfolio.TabIndex = 4; refreshButtonPortfolio.Text = "تازه‌سازی";
            stocksDataGridView.AllowUserToAddRows = false; stocksDataGridView.AllowUserToDeleteRows = false; stocksDataGridView.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right; stocksDataGridView.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill; stocksDataGridView.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize; stocksDataGridView.Columns.AddRange(new DataGridViewColumn[] { rowColumn, symbolColumn, lastTradeColumn, selectColumn }); stocksDataGridView.Location = new Point(8, 47); stocksDataGridView.Name = "stocksDataGridView"; stocksDataGridView.RightToLeft = RightToLeft.Yes; stocksDataGridView.RowHeadersVisible = false; stocksDataGridView.RowHeadersWidth = 51; stocksDataGridView.SelectionMode = DataGridViewSelectionMode.FullRowSelect; stocksDataGridView.Size = new Size(391, 548); stocksDataGridView.TabIndex = 0;
            rowColumn.FillWeight = 121.334824F; rowColumn.HeaderText = "ردیف"; rowColumn.MinimumWidth = 6; rowColumn.Name = "rowColumn"; symbolColumn.FillWeight = 149.73262F; symbolColumn.HeaderText = "نماد"; symbolColumn.MinimumWidth = 6; symbolColumn.Name = "symbolColumn"; lastTradeColumn.FillWeight = 87.110054F; lastTradeColumn.HeaderText = "آخرین معامله"; lastTradeColumn.MinimumWidth = 6; lastTradeColumn.Name = "lastTradeColumn"; selectColumn.FalseValue = false; selectColumn.FillWeight = 41.8225136F; selectColumn.HeaderText = "انتخاب"; selectColumn.MinimumWidth = 6; selectColumn.Name = "selectColumn"; selectColumn.TrueValue = true;
            stocksBottomPanel.Anchor = AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right; stocksBottomPanel.Controls.Add(refreshButton); stocksBottomPanel.Controls.Add(navigationSpeedTextBox); stocksBottomPanel.Controls.Add(speedLabel); stocksBottomPanel.Controls.Add(navigationButton); stocksBottomPanel.Controls.Add(newPortfolioButton); stocksBottomPanel.Controls.Add(deleteButton); stocksBottomPanel.Controls.Add(selectNoneCheckBox); stocksBottomPanel.Controls.Add(selectAllCheckBox); stocksBottomPanel.FlowDirection = FlowDirection.RightToLeft; stocksBottomPanel.Location = new Point(8, 601); stocksBottomPanel.Name = "stocksBottomPanel"; stocksBottomPanel.Padding = new Padding(4); stocksBottomPanel.Size = new Size(391, 97); stocksBottomPanel.TabIndex = 1;
            refreshButton.Location = new Point(7, 7); refreshButton.Name = "refreshButton"; refreshButton.Size = new Size(91, 34); refreshButton.TabIndex = 2; refreshButton.Text = "تازه‌سازی"; navigationSpeedTextBox.Location = new Point(104, 10); navigationSpeedTextBox.Margin = new Padding(2, 6, 3, 3); navigationSpeedTextBox.Name = "navigationSpeedTextBox"; navigationSpeedTextBox.Size = new Size(62, 31); navigationSpeedTextBox.TabIndex = 7; navigationSpeedTextBox.Text = "1000"; speedLabel.AutoSize = true; speedLabel.Location = new Point(170, 13); speedLabel.Margin = new Padding(7, 9, 2, 3); speedLabel.Name = "speedLabel"; speedLabel.Size = new Size(64, 25); speedLabel.TabIndex = 6; speedLabel.Text = "سرعت:"; navigationButton.Location = new Point(244, 7); navigationButton.Name = "navigationButton"; navigationButton.Size = new Size(81, 34); navigationButton.TabIndex = 0; navigationButton.Text = "پیمایش"; newPortfolioButton.Location = new Point(7, 47); newPortfolioButton.Name = "newPortfolioButton"; newPortfolioButton.Size = new Size(91, 35); newPortfolioButton.TabIndex = 1; newPortfolioButton.Text = "سبد جدید"; deleteButton.Location = new Point(104, 47); deleteButton.Name = "deleteButton"; deleteButton.Size = new Size(92, 35); deleteButton.TabIndex = 3; deleteButton.Text = "حذف"; selectNoneCheckBox.AutoSize = true; selectNoneCheckBox.Location = new Point(202, 53); selectNoneCheckBox.Margin = new Padding(7, 9, 3, 3); selectNoneCheckBox.Name = "selectNoneCheckBox"; selectNoneCheckBox.Size = new Size(64, 29); selectNoneCheckBox.TabIndex = 5; selectNoneCheckBox.Text = "هیچ"; selectAllCheckBox.AutoSize = true; selectAllCheckBox.Location = new Point(276, 53); selectAllCheckBox.Margin = new Padding(7, 9, 3, 3); selectAllCheckBox.Name = "selectAllCheckBox"; selectAllCheckBox.Size = new Size(66, 29); selectAllCheckBox.TabIndex = 4; selectAllCheckBox.Text = "همه"; portfolioComboBox.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right; portfolioComboBox.DropDownStyle = ComboBoxStyle.DropDownList; portfolioComboBox.Location = new Point(108, 8); portfolioComboBox.Name = "portfolioComboBox"; portfolioComboBox.Size = new Size(287, 33); portfolioComboBox.TabIndex = 2; portfolioLabel.Anchor = AnchorStyles.Top | AnchorStyles.Right; portfolioLabel.AutoSize = true; portfolioLabel.Location = new Point(497, 12); portfolioLabel.Name = "portfolioLabel"; portfolioLabel.Size = new Size(46, 25); portfolioLabel.TabIndex = 3; portfolioLabel.Text = "سبد:";
            ClientSize = new Size(1288, 780); Controls.Add(mainSplitContainer); Controls.Add(mainMenuStrip); MainMenuStrip = mainMenuStrip; MinimumSize = new Size(900, 600); Name = "Form1"; RightToLeft = RightToLeft.No; StartPosition = FormStartPosition.CenterScreen; Text = "Trade.It"; WindowState = FormWindowState.Maximized;
            mainMenuStrip.ResumeLayout(false); mainMenuStrip.PerformLayout(); mainSplitContainer.Panel1.ResumeLayout(false); mainSplitContainer.Panel2.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)mainSplitContainer).EndInit(); mainSplitContainer.ResumeLayout(false); chartPanel.ResumeLayout(false); chartTabControl.ResumeLayout(false); chartTabPage.ResumeLayout(false); chartInfoPanel.ResumeLayout(false); chartToolbarPanel.ResumeLayout(false); controlTabControl.ResumeLayout(false); stocksTabPage.ResumeLayout(false); stocksTabPage.PerformLayout(); ((System.ComponentModel.ISupportInitialize)stocksDataGridView).EndInit(); stocksBottomPanel.ResumeLayout(false); stocksBottomPanel.PerformLayout(); ResumeLayout(false); PerformLayout();
        }
    }
}