namespace Trade.It
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.MenuStrip mainMenuStrip;
        private System.Windows.Forms.ToolStripMenuItem portfolioDefinitionMenuItem;
        private System.Windows.Forms.ToolStripMenuItem portfolioManagementMenuItem;
        private System.Windows.Forms.ToolStripMenuItem settingsMenuItem;
        private System.Windows.Forms.ToolStripMenuItem resetMenuItem;
        private System.Windows.Forms.ToolStripMenuItem closeAllChartsMenuItem;

        private System.Windows.Forms.SplitContainer mainSplitContainer;
        private System.Windows.Forms.TabControl controlTabControl;
        private System.Windows.Forms.TabPage stocksTabPage;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.TabPage tabPage3;
        private System.Windows.Forms.TabPage marketsTabPage;

        private System.Windows.Forms.ComboBox portfolioComboBox;
        private System.Windows.Forms.Label portfolioLabel;
        private System.Windows.Forms.DataGridView stocksDataGridView;
        private System.Windows.Forms.Button navigationButton;
        private System.Windows.Forms.Button newPortfolioButton;
        private System.Windows.Forms.Button refreshButton;
        private System.Windows.Forms.Button deleteButton;
        private System.Windows.Forms.CheckBox selectAllCheckBox;
        private System.Windows.Forms.CheckBox selectNoneCheckBox;
        private System.Windows.Forms.Label speedLabel;
        private System.Windows.Forms.TextBox navigationSpeedTextBox;
        private System.Windows.Forms.Panel chartPanel;
        private System.Windows.Forms.Panel chartToolbarPanel;
        private System.Windows.Forms.ComboBox chartTypeComboBox;
        private System.Windows.Forms.Button gridButton;
        private System.Windows.Forms.Button crossButton;
        private System.Windows.Forms.Button zoomInButton;
        private System.Windows.Forms.Button zoomOutButton;
        private System.Windows.Forms.Button resetChartButton;
        private System.Windows.Forms.Button hideChartButton;
        private System.Windows.Forms.Button hideToolsButton;
        private System.Windows.Forms.Button printChartButton;
        private System.Windows.Forms.Button snapshotChartButton;
        private System.Windows.Forms.Button fullScreenChartButton;
        private System.Windows.Forms.TabControl chartTabControl;
        private System.Windows.Forms.TabPage chartTabPage;
        private System.Windows.Forms.Panel chartInfoPanel;
        private System.Windows.Forms.Label chartInfoLabel;
        private System.Windows.Forms.Label chartPlaceholderLabel;
        private System.Windows.Forms.DataGridViewTextBoxColumn rowColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn symbolColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn lastTradeColumn;
        private System.Windows.Forms.DataGridViewCheckBoxColumn selectColumn;
        private System.Windows.Forms.Button refreshButtonPortfolio;

        private System.Windows.Forms.GroupBox tradingStatusGroup;
        private System.Windows.Forms.RadioButton statusAllRadio;
        private System.Windows.Forms.RadioButton statusPositiveRadio;
        private System.Windows.Forms.RadioButton statusNegativeRadio;
        private System.Windows.Forms.GroupBox nameFilterGroup;
        private System.Windows.Forms.ComboBox nameComboBox;
        private System.Windows.Forms.TextBox nameTextBox;
        private System.Windows.Forms.GroupBox volumeRatioGroup;
        private System.Windows.Forms.TextBox volumeRatioTextBox;
        private System.Windows.Forms.ComboBox volumeRatioOperatorComboBox;
        private System.Windows.Forms.GroupBox pastDaysGroup;
        private System.Windows.Forms.TextBox pastDaysTextBox;
        private System.Windows.Forms.ComboBox pastDaysStatusComboBox;
        private System.Windows.Forms.GroupBox comparisonGroup;
        private System.Windows.Forms.ComboBox comparisonFirstComboBox;
        private System.Windows.Forms.ComboBox comparisonOperatorComboBox;
        private System.Windows.Forms.ComboBox comparisonSecondComboBox;
        private System.Windows.Forms.TextBox comparisonFirstTextBox;
        private System.Windows.Forms.TextBox comparisonSecondTextBox;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label8;

        private System.Windows.Forms.GroupBox comparisonGroup6;
        private System.Windows.Forms.ComboBox comparisonFirstComboBox6;
        private System.Windows.Forms.ComboBox comparisonOperatorComboBox6;
        private System.Windows.Forms.ComboBox comparisonSecondComboBox6;
        private System.Windows.Forms.TextBox comparisonFirstTextBox6;
        private System.Windows.Forms.TextBox comparisonSecondTextBox6;
        private System.Windows.Forms.Label label5_6;
        private System.Windows.Forms.Label label6_6;
        private System.Windows.Forms.Label label8_6;

        private System.Windows.Forms.GroupBox comparisonGroup7;
        private System.Windows.Forms.ComboBox comparisonFirstComboBox7;
        private System.Windows.Forms.ComboBox comparisonOperatorComboBox7;
        private System.Windows.Forms.ComboBox comparisonSecondComboBox7;
        private System.Windows.Forms.TextBox comparisonFirstTextBox7;
        private System.Windows.Forms.TextBox comparisonSecondTextBox7;
        private System.Windows.Forms.Label label5_7;
        private System.Windows.Forms.Label label6_7;
        private System.Windows.Forms.Label label8_7;

        private System.Windows.Forms.GroupBox comparisonGroup8;
        private System.Windows.Forms.ComboBox comparisonFirstComboBox8;
        private System.Windows.Forms.ComboBox comparisonOperatorComboBox8;
        private System.Windows.Forms.ComboBox comparisonSecondComboBox8;
        private System.Windows.Forms.TextBox comparisonFirstTextBox8;
        private System.Windows.Forms.TextBox comparisonSecondTextBox8;
        private System.Windows.Forms.Label label5_8;
        private System.Windows.Forms.Label label6_8;
        private System.Windows.Forms.Label label8_8;

        private System.Windows.Forms.GroupBox ohlcChangeFilterGroup;
        private System.Windows.Forms.ComboBox ohlcChangeFieldComboBox;
        private System.Windows.Forms.TextBox ohlcChangeDaysTextBox;
        private System.Windows.Forms.TextBox ohlcChangePercentTextBox;
        private System.Windows.Forms.ComboBox ohlcChangeDirectionComboBox;
        private System.Windows.Forms.Label ohlcChangeFieldLabel;
        private System.Windows.Forms.Label ohlcChangeDaysLabel;
        private System.Windows.Forms.Label ohlcChangePercentLabel;

        private System.Windows.Forms.Button clearFiltersButton;

        private System.Windows.Forms.GroupBox identifierMainGroup;
        private System.Windows.Forms.TableLayoutPanel identifierLayout;
        private System.Windows.Forms.Label identifierSymbolLabel;
        private System.Windows.Forms.TextBox identifierSymbolTextBox;
        private System.Windows.Forms.Label identifierNameLabel;
        private System.Windows.Forms.TextBox identifierNameTextBox;
        private System.Windows.Forms.Label identifierTsetmcLabel;
        private System.Windows.Forms.TextBox identifierTsetmcTextBox;
        private System.Windows.Forms.Label identifierMarketLabel;
        private System.Windows.Forms.ComboBox identifierMarketComboBox;
        private System.Windows.Forms.Label identifierGroupLabel;
        private System.Windows.Forms.TextBox identifierGroupTextBox;
        private System.Windows.Forms.Label identifierDescriptionLabel;
        private System.Windows.Forms.TextBox identifierDescriptionTextBox;

        private System.Windows.Forms.Label marketTypeLabel;
        private System.Windows.Forms.TextBox marketTypeTextBox;
        private System.Windows.Forms.Label marketNameLabel;
        private System.Windows.Forms.TextBox marketNameTextBox;
        private System.Windows.Forms.Label marketBoardLabel;
        private System.Windows.Forms.TextBox marketBoardTextBox;
        private System.Windows.Forms.Label marketIndustryGroupLabel;
        private System.Windows.Forms.TextBox marketIndustryGroupTextBox;
        private System.Windows.Forms.Label marketSubIndustryGroupLabel;
        private System.Windows.Forms.TextBox marketSubIndustryGroupTextBox;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            mainMenuStrip = new MenuStrip();
            portfolioDefinitionMenuItem = new ToolStripMenuItem();
            portfolioManagementMenuItem = new ToolStripMenuItem();
            settingsMenuItem = new ToolStripMenuItem();
            resetMenuItem = new ToolStripMenuItem();
            closeAllChartsMenuItem = new ToolStripMenuItem();
            mainSplitContainer = new SplitContainer();
            chartPanel = new Panel();
            chartTabControl = new TabControl();
            chartTabPage = new TabPage();
            chartInfoPanel = new Panel();
            chartInfoLabel = new Label();
            chartPlaceholderLabel = new Label();
            chartToolbarPanel = new Panel();
            chartTypeComboBox = new ComboBox();
            gridButton = new Button();
            crossButton = new Button();
            zoomInButton = new Button();
            zoomOutButton = new Button();
            resetChartButton = new Button();
            hideChartButton = new Button();
            hideToolsButton = new Button();
            printChartButton = new Button();
            snapshotChartButton = new Button();
            fullScreenChartButton = new Button();
            controlTabControl = new TabControl();
            stocksTabPage = new TabPage();
            groupBox1 = new GroupBox();
            navigationButton = new Button();
            refreshButton = new Button();
            selectNoneCheckBox = new CheckBox();
            speedLabel = new Label();
            deleteButton = new Button();
            selectAllCheckBox = new CheckBox();
            navigationSpeedTextBox = new TextBox();
            newPortfolioButton = new Button();
            refreshButtonPortfolio = new Button();
            stocksDataGridView = new DataGridView();
            rowColumn = new DataGridViewTextBoxColumn();
            symbolColumn = new DataGridViewTextBoxColumn();
            lastTradeColumn = new DataGridViewTextBoxColumn();
            selectColumn = new DataGridViewCheckBoxColumn();
            portfolioComboBox = new ComboBox();
            portfolioLabel = new Label();
            tabPage2 = new TabPage();
            clearFiltersButton = new Button();
            ohlcChangeFilterGroup = new GroupBox();
            ohlcChangeFieldComboBox = new ComboBox();
            ohlcChangeDaysTextBox = new TextBox();
            ohlcChangePercentTextBox = new TextBox();
            ohlcChangeDirectionComboBox = new ComboBox();
            ohlcChangeFieldLabel = new Label();
            ohlcChangeDaysLabel = new Label();
            ohlcChangePercentLabel = new Label();
            comparisonGroup8 = new GroupBox();
            label8_8 = new Label();
            comparisonSecondTextBox8 = new TextBox();
            label6_8 = new Label();
            comparisonFirstTextBox8 = new TextBox();
            label5_8 = new Label();
            comparisonFirstComboBox8 = new ComboBox();
            comparisonOperatorComboBox8 = new ComboBox();
            comparisonSecondComboBox8 = new ComboBox();
            comparisonGroup7 = new GroupBox();
            label8_7 = new Label();
            comparisonSecondTextBox7 = new TextBox();
            label6_7 = new Label();
            comparisonFirstTextBox7 = new TextBox();
            label5_7 = new Label();
            comparisonFirstComboBox7 = new ComboBox();
            comparisonOperatorComboBox7 = new ComboBox();
            comparisonSecondComboBox7 = new ComboBox();
            comparisonGroup6 = new GroupBox();
            label8_6 = new Label();
            comparisonSecondTextBox6 = new TextBox();
            label6_6 = new Label();
            comparisonFirstTextBox6 = new TextBox();
            label5_6 = new Label();
            comparisonFirstComboBox6 = new ComboBox();
            comparisonOperatorComboBox6 = new ComboBox();
            comparisonSecondComboBox6 = new ComboBox();
            comparisonGroup = new GroupBox();
            label8 = new Label();
            comparisonSecondTextBox = new TextBox();
            label6 = new Label();
            comparisonFirstTextBox = new TextBox();
            label5 = new Label();
            comparisonFirstComboBox = new ComboBox();
            comparisonOperatorComboBox = new ComboBox();
            comparisonSecondComboBox = new ComboBox();
            pastDaysGroup = new GroupBox();
            label4 = new Label();
            label3 = new Label();
            pastDaysTextBox = new TextBox();
            pastDaysStatusComboBox = new ComboBox();
            volumeRatioGroup = new GroupBox();
            label2 = new Label();
            label1 = new Label();
            textBox1 = new TextBox();
            volumeRatioTextBox = new TextBox();
            volumeRatioOperatorComboBox = new ComboBox();
            nameFilterGroup = new GroupBox();
            nameComboBox = new ComboBox();
            nameTextBox = new TextBox();
            tradingStatusGroup = new GroupBox();
            statusAllRadio = new RadioButton();
            statusPositiveRadio = new RadioButton();
            statusNegativeRadio = new RadioButton();
            tabPage3 = new TabPage();
            identifierMainGroup = new GroupBox();
            identifierLayout = new TableLayoutPanel();
            identifierSymbolLabel = new Label();
            identifierSymbolTextBox = new TextBox();
            identifierNameLabel = new Label();
            identifierNameTextBox = new TextBox();
            identifierTsetmcLabel = new Label();
            identifierTsetmcTextBox = new TextBox();
            identifierMarketLabel = new Label();
            identifierMarketComboBox = new ComboBox();
            identifierGroupLabel = new Label();
            identifierGroupTextBox = new TextBox();
            identifierDescriptionLabel = new Label();
            identifierDescriptionTextBox = new TextBox();
            marketsTabPage = new TabPage();
            marketTypeLabel = new Label();
            marketTypeTextBox = new TextBox();
            marketNameLabel = new Label();
            marketNameTextBox = new TextBox();
            marketBoardLabel = new Label();
            marketBoardTextBox = new TextBox();
            marketIndustryGroupLabel = new Label();
            marketIndustryGroupTextBox = new TextBox();
            marketSubIndustryGroupLabel = new Label();
            marketSubIndustryGroupTextBox = new TextBox();
            mainMenuStrip.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)mainSplitContainer).BeginInit();
            mainSplitContainer.Panel1.SuspendLayout();
            mainSplitContainer.Panel2.SuspendLayout();
            mainSplitContainer.SuspendLayout();
            chartPanel.SuspendLayout();
            chartTabControl.SuspendLayout();
            chartTabPage.SuspendLayout();
            chartInfoPanel.SuspendLayout();
            chartToolbarPanel.SuspendLayout();
            controlTabControl.SuspendLayout();
            stocksTabPage.SuspendLayout();
            groupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)stocksDataGridView).BeginInit();
            tabPage2.SuspendLayout();
            ohlcChangeFilterGroup.SuspendLayout();
            comparisonGroup8.SuspendLayout();
            comparisonGroup7.SuspendLayout();
            comparisonGroup6.SuspendLayout();
            comparisonGroup.SuspendLayout();
            pastDaysGroup.SuspendLayout();
            volumeRatioGroup.SuspendLayout();
            nameFilterGroup.SuspendLayout();
            tradingStatusGroup.SuspendLayout();
            tabPage3.SuspendLayout();
            identifierMainGroup.SuspendLayout();
            identifierLayout.SuspendLayout();
            marketsTabPage.SuspendLayout();
            SuspendLayout();
            mainMenuStrip.ImageScalingSize = new Size(20, 20);
            mainMenuStrip.Items.AddRange(new ToolStripItem[] { portfolioDefinitionMenuItem, portfolioManagementMenuItem, settingsMenuItem, resetMenuItem, closeAllChartsMenuItem });
            mainMenuStrip.Location = new Point(0, 0);
            mainMenuStrip.Name = "mainMenuStrip";
            mainMenuStrip.RightToLeft = RightToLeft.No;
            mainMenuStrip.Size = new Size(1452, 33);
            mainMenuStrip.TabIndex = 0;
            portfolioDefinitionMenuItem.Name = "portfolioDefinitionMenuItem";
            portfolioDefinitionMenuItem.Size = new Size(114, 29);
            portfolioDefinitionMenuItem.Text = "تعریف سبد";
            portfolioManagementMenuItem.Name = "portfolioManagementMenuItem";
            portfolioManagementMenuItem.Size = new Size(122, 29);
            portfolioManagementMenuItem.Text = "مدیریت سبد";
            settingsMenuItem.Name = "settingsMenuItem";
            settingsMenuItem.Size = new Size(94, 29);
            settingsMenuItem.Text = "تنظیمات";
            resetMenuItem.Name = "resetMenuItem";
            resetMenuItem.Size = new Size(92, 29);
            resetMenuItem.Text = "بازنشانی";
            closeAllChartsMenuItem.Name = "closeAllChartsMenuItem";
            closeAllChartsMenuItem.Size = new Size(104, 29);
            closeAllChartsMenuItem.Text = "بستن همه";
            mainSplitContainer.Dock = DockStyle.Fill;
            mainSplitContainer.Location = new Point(0, 33);
            mainSplitContainer.Name = "mainSplitContainer";
            mainSplitContainer.Panel1.Controls.Add(controlTabControl);
            mainSplitContainer.Panel1MinSize = 300;
            mainSplitContainer.Panel2.Controls.Add(chartPanel);
            mainSplitContainer.Panel2MinSize = 500;
            mainSplitContainer.Size = new Size(1452, 825);
            mainSplitContainer.SplitterDistance = 368;
            mainSplitContainer.TabIndex = 1;
            chartPanel.BorderStyle = BorderStyle.FixedSingle;
            chartPanel.Controls.Add(chartTabControl);
            chartPanel.Controls.Add(chartToolbarPanel);
            chartPanel.Dock = DockStyle.Fill;
            chartPanel.Location = new Point(0, 0);
            chartPanel.Name = "chartPanel";
            chartPanel.Size = new Size(1084, 825);
            chartPanel.TabIndex = 0;
            chartTabControl.Controls.Add(chartTabPage);
            chartTabControl.Dock = DockStyle.Fill;
            chartTabControl.Location = new Point(0, 51);
            chartTabControl.Name = "chartTabControl";
            chartTabControl.SelectedIndex = 0;
            chartTabControl.Size = new Size(1082, 772);
            chartTabControl.TabIndex = 0;
            chartTabPage.Controls.Add(chartInfoPanel);
            chartTabPage.Controls.Add(chartPlaceholderLabel);
            chartTabPage.Location = new Point(4, 34);
            chartTabPage.Name = "chartTabPage";
            chartTabPage.Padding = new Padding(3);
            chartTabPage.Size = new Size(1074, 734);
            chartTabPage.TabIndex = 0;
            chartTabPage.Text = "نماد";
            chartInfoPanel.BackColor = SystemColors.Control;
            chartInfoPanel.Controls.Add(chartInfoLabel);
            chartInfoPanel.Dock = DockStyle.Top;
            chartInfoPanel.Location = new Point(3, 3);
            chartInfoPanel.Name = "chartInfoPanel";
            chartInfoPanel.Size = new Size(1068, 30);
            chartInfoPanel.TabIndex = 0;
            chartInfoLabel.Dock = DockStyle.Fill;
            chartInfoLabel.Location = new Point(0, 0);
            chartInfoLabel.Name = "chartInfoLabel";
            chartInfoLabel.Padding = new Padding(8, 0, 0, 0);
            chartInfoLabel.Size = new Size(1068, 30);
            chartInfoLabel.TabIndex = 0;
            chartInfoLabel.Text = "O: —    H: —    L: —    C: —    V: — تاریخ/زمان : —    ";
            chartInfoLabel.TextAlign = ContentAlignment.MiddleLeft;
            chartPlaceholderLabel.Dock = DockStyle.Fill;
            chartPlaceholderLabel.Font = new Font("Segoe UI", 14F);
            chartPlaceholderLabel.Location = new Point(3, 3);
            chartPlaceholderLabel.Name = "chartPlaceholderLabel";
            chartPlaceholderLabel.Size = new Size(1068, 728);
            chartPlaceholderLabel.TabIndex = 1;
            chartPlaceholderLabel.Text = "ناحیه رسم چارت";
            chartPlaceholderLabel.TextAlign = ContentAlignment.MiddleCenter;
            chartToolbarPanel.BorderStyle = BorderStyle.FixedSingle;
            chartToolbarPanel.Controls.Add(chartTypeComboBox);
            chartToolbarPanel.Controls.Add(gridButton);
            chartToolbarPanel.Controls.Add(crossButton);
            chartToolbarPanel.Controls.Add(zoomInButton);
            chartToolbarPanel.Controls.Add(zoomOutButton);
            chartToolbarPanel.Controls.Add(resetChartButton);
            chartToolbarPanel.Controls.Add(hideChartButton);
            chartToolbarPanel.Controls.Add(hideToolsButton);
            chartToolbarPanel.Controls.Add(printChartButton);
            chartToolbarPanel.Controls.Add(snapshotChartButton);
            chartToolbarPanel.Controls.Add(fullScreenChartButton);
            chartToolbarPanel.Dock = DockStyle.Top;
            chartToolbarPanel.Location = new Point(0, 0);
            chartToolbarPanel.Name = "chartToolbarPanel";
            chartToolbarPanel.Padding = new Padding(6, 5, 6, 5);
            chartToolbarPanel.RightToLeft = RightToLeft.Yes;
            chartToolbarPanel.Size = new Size(1082, 51);
            chartToolbarPanel.TabIndex = 1;
            chartTypeComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            chartTypeComboBox.Items.AddRange(new object[] { "شمعی", "خطی", "میله ای" });
            chartTypeComboBox.Location = new Point(6, 8);
            chartTypeComboBox.Name = "chartTypeComboBox";
            chartTypeComboBox.Size = new Size(92, 33);
            chartTypeComboBox.TabIndex = 0;
            gridButton.Location = new Point(99, 7);
            gridButton.Name = "gridButton";
            gridButton.Size = new Size(54, 34);
            gridButton.TabIndex = 1;
            gridButton.Text = "گرید";
            crossButton.Location = new Point(154, 7);
            crossButton.Name = "crossButton";
            crossButton.Size = new Size(58, 34);
            crossButton.TabIndex = 2;
            crossButton.Text = "Cross";
            zoomInButton.Location = new Point(211, 7);
            zoomInButton.Name = "zoomInButton";
            zoomInButton.Size = new Size(54, 34);
            zoomInButton.TabIndex = 3;
            zoomInButton.Text = "+";
            zoomOutButton.Location = new Point(266, 7);
            zoomOutButton.Name = "zoomOutButton";
            zoomOutButton.Size = new Size(54, 34);
            zoomOutButton.TabIndex = 4;
            zoomOutButton.Text = "-";
            resetChartButton.Location = new Point(321, 7);
            resetChartButton.Name = "resetChartButton";
            resetChartButton.Size = new Size(72, 34);
            resetChartButton.TabIndex = 5;
            resetChartButton.Text = "بازنشانی";
            hideChartButton.Location = new Point(394, 7);
            hideChartButton.Name = "hideChartButton";
            hideChartButton.Size = new Size(66, 34);
            hideChartButton.TabIndex = 6;
            hideChartButton.Text = "پنهان";
            hideToolsButton.Location = new Point(461, 7);
            hideToolsButton.Name = "hideToolsButton";
            hideToolsButton.Size = new Size(70, 34);
            hideToolsButton.TabIndex = 7;
            hideToolsButton.Text = "ابزارها";
            printChartButton.Location = new Point(532, 7);
            printChartButton.Name = "printChartButton";
            printChartButton.Size = new Size(70, 34);
            printChartButton.TabIndex = 8;
            printChartButton.Text = "چاپ";
            snapshotChartButton.Location = new Point(603, 7);
            snapshotChartButton.Name = "snapshotChartButton";
            snapshotChartButton.Size = new Size(86, 34);
            snapshotChartButton.TabIndex = 9;
            snapshotChartButton.Text = "تصویر";
            fullScreenChartButton.Location = new Point(690, 7);
            fullScreenChartButton.Name = "fullScreenChartButton";
            fullScreenChartButton.Size = new Size(95, 34);
            fullScreenChartButton.TabIndex = 10;
            fullScreenChartButton.Text = "تمام صفحه";
            controlTabControl.Controls.Add(stocksTabPage);
            controlTabControl.Controls.Add(tabPage2);
            controlTabControl.Controls.Add(tabPage3);
            controlTabControl.Controls.Add(marketsTabPage);
            controlTabControl.Dock = DockStyle.Fill;
            controlTabControl.Location = new Point(0, 0);
            controlTabControl.Name = "controlTabControl";
            controlTabControl.SelectedIndex = 0;
            controlTabControl.Size = new Size(368, 825);
            controlTabControl.TabIndex = 0;
            stocksTabPage.Controls.Add(groupBox1);
            stocksTabPage.Controls.Add(stocksDataGridView);
            stocksTabPage.Location = new Point(4, 34);
            stocksTabPage.Name = "stocksTabPage";
            stocksTabPage.Padding = new Padding(8);
            stocksTabPage.Size = new Size(360, 787);
            stocksTabPage.TabIndex = 0;
            stocksTabPage.Text = "سبد";
            groupBox1.Dock = DockStyle.Top;
            groupBox1.Location = new Point(8, 8);
            groupBox1.Name = "groupBox1";
            groupBox1.Size = new Size(344, 96);
            groupBox1.TabIndex = 0;
            groupBox1.TabStop = false;
            groupBox1.Text = "کنترل سبد";
            groupBox1.Controls.Add(navigationButton);
            groupBox1.Controls.Add(refreshButton);
            groupBox1.Controls.Add(selectNoneCheckBox);
            groupBox1.Controls.Add(speedLabel);
            groupBox1.Controls.Add(deleteButton);
            groupBox1.Controls.Add(selectAllCheckBox);
            groupBox1.Controls.Add(navigationSpeedTextBox);
            groupBox1.Controls.Add(newPortfolioButton);
            groupBox1.Controls.Add(refreshButtonPortfolio);
            stocksDataGridView.Dock = DockStyle.Fill;
            stocksDataGridView.Location = new Point(8, 104);
            stocksDataGridView.Name = "stocksDataGridView";
            stocksDataGridView.Size = new Size(344, 675);
            stocksDataGridView.TabIndex = 1;
            rowColumn.HeaderText = "ردیف";
            rowColumn.Name = "rowColumn";
            symbolColumn.HeaderText = "نماد";
            symbolColumn.Name = "symbolColumn";
            lastTradeColumn.HeaderText = "آخرین معامله";
            lastTradeColumn.Name = "lastTradeColumn";
            selectColumn.HeaderText = "انتخاب";
            selectColumn.Name = "selectColumn";
            portfolioComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            portfolioComboBox.Location = new Point(108, 8);
            portfolioComboBox.Name = "portfolioComboBox";
            portfolioComboBox.Size = new Size(236, 33);
            portfolioComboBox.TabIndex = 2;
            portfolioLabel.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            portfolioLabel.AutoSize = true;
            portfolioLabel.Location = new Point(446, 12);
            portfolioLabel.Name = "portfolioLabel";
            portfolioLabel.Size = new Size(46, 25);
            portfolioLabel.TabIndex = 3;
            portfolioLabel.Text = "سبد:";
            tabPage2.AutoScroll = true;
            tabPage2.Controls.Add(clearFiltersButton);
            tabPage2.Controls.Add(ohlcChangeFilterGroup);
            tabPage2.Controls.Add(comparisonGroup8);
            tabPage2.Controls.Add(comparisonGroup7);
            tabPage2.Controls.Add(comparisonGroup6);
            tabPage2.Controls.Add(comparisonGroup);
            tabPage2.Controls.Add(pastDaysGroup);
            tabPage2.Controls.Add(volumeRatioGroup);
            tabPage2.Controls.Add(nameFilterGroup);
            tabPage2.Controls.Add(tradingStatusGroup);
            tabPage2.Location = new Point(4, 34);
            tabPage2.Name = "tabPage2";
            tabPage2.Padding = new Padding(8);
            tabPage2.Size = new Size(356, 787);
            tabPage2.TabIndex = 1;
            tabPage2.Text = "فیلترها";
            clearFiltersButton.Location = new Point(8, 981);
            clearFiltersButton.Name = "clearFiltersButton";
            clearFiltersButton.Size = new Size(314, 36);
            clearFiltersButton.TabIndex = 9;
            clearFiltersButton.Text = "پاک کردن";
            clearFiltersButton.UseVisualStyleBackColor = true;
            ohlcChangeFilterGroup.Controls.Add(ohlcChangeFieldLabel);
            ohlcChangeFilterGroup.Controls.Add(ohlcChangeFieldComboBox);
            ohlcChangeFilterGroup.Controls.Add(ohlcChangeDaysLabel);
            ohlcChangeFilterGroup.Controls.Add(ohlcChangeDaysTextBox);
            ohlcChangeFilterGroup.Controls.Add(ohlcChangePercentLabel);
            ohlcChangeFilterGroup.Controls.Add(ohlcChangePercentTextBox);
            ohlcChangeFilterGroup.Controls.Add(ohlcChangeDirectionComboBox);
            ohlcChangeFilterGroup.Dock = DockStyle.Top;
            ohlcChangeFilterGroup.Location = new Point(8, 876);
            ohlcChangeFilterGroup.Name = "ohlcChangeFilterGroup";
            ohlcChangeFilterGroup.Size = new Size(314, 105);
            ohlcChangeFilterGroup.TabIndex = 8;
            ohlcChangeFilterGroup.TabStop = false;
            ohlcChangeFilterGroup.Text = "9. رشد/افت OHLC:";
            ohlcChangeFieldLabel.AutoSize = true;
            ohlcChangeFieldLabel.Location = new Point(274, 38);
            ohlcChangeFieldLabel.Name = "ohlcChangeFieldLabel";
            ohlcChangeFieldLabel.Size = new Size(35, 25);
            ohlcChangeFieldLabel.TabIndex = 0;
            ohlcChangeFieldLabel.Text = "قیمت";
            ohlcChangeFieldComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            ohlcChangeFieldComboBox.Items.AddRange(new object[] { "O", "H", "L", "C", "پایانی" });
            ohlcChangeFieldComboBox.Location = new Point(210, 34);
            ohlcChangeFieldComboBox.Name = "ohlcChangeFieldComboBox";
            ohlcChangeFieldComboBox.Size = new Size(60, 33);
            ohlcChangeFieldComboBox.TabIndex = 1;
            ohlcChangeDaysLabel.AutoSize = true;
            ohlcChangeDaysLabel.Location = new Point(119, 38);
            ohlcChangeDaysLabel.Name = "ohlcChangeDaysLabel";
            ohlcChangeDaysLabel.Size = new Size(81, 25);
            ohlcChangeDaysLabel.TabIndex = 2;
            ohlcChangeDaysLabel.Text = "کندل قبل";
            ohlcChangeDaysTextBox.Location = new Point(62, 34);
            ohlcChangeDaysTextBox.Name = "ohlcChangeDaysTextBox";
            ohlcChangeDaysTextBox.Size = new Size(57, 31);
            ohlcChangeDaysTextBox.TabIndex = 3;
            ohlcChangeDaysTextBox.Text = "5";
            ohlcChangeDaysTextBox.TextAlign = HorizontalAlignment.Center;
            ohlcChangePercentLabel.AutoSize = true;
            ohlcChangePercentLabel.Location = new Point(274, 73);
            ohlcChangePercentLabel.Name = "ohlcChangePercentLabel";
            ohlcChangePercentLabel.Size = new Size(22, 25);
            ohlcChangePercentLabel.TabIndex = 4;
            ohlcChangePercentLabel.Text = "%";
            ohlcChangePercentTextBox.Location = new Point(210, 70);
            ohlcChangePercentTextBox.Name = "ohlcChangePercentTextBox";
            ohlcChangePercentTextBox.Size = new Size(60, 31);
            ohlcChangePercentTextBox.TabIndex = 5;
            ohlcChangePercentTextBox.Text = "5";
            ohlcChangePercentTextBox.TextAlign = HorizontalAlignment.Center;
            ohlcChangeDirectionComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            ohlcChangeDirectionComboBox.Items.AddRange(new object[] { "رشد حداقل", "افت حداقل" });
            ohlcChangeDirectionComboBox.Location = new Point(62, 69);
            ohlcChangeDirectionComboBox.Name = "ohlcChangeDirectionComboBox";
            ohlcChangeDirectionComboBox.Size = new Size(142, 33);
            ohlcChangeDirectionComboBox.TabIndex = 6;
            comparisonGroup8.Controls.Add(label8_8);
            comparisonGroup8.Controls.Add(comparisonSecondTextBox8);
            comparisonGroup8.Controls.Add(label6_8);
            comparisonGroup8.Controls.Add(comparisonFirstTextBox8);
            comparisonGroup8.Controls.Add(label5_8);
            comparisonGroup8.Controls.Add(comparisonFirstComboBox8);
            comparisonGroup8.Controls.Add(comparisonOperatorComboBox8);
            comparisonGroup8.Controls.Add(comparisonSecondComboBox8);
            comparisonGroup8.Dock = DockStyle.Top;
            comparisonGroup8.Location = new Point(8, 757);
            comparisonGroup8.Name = "comparisonGroup8";
            comparisonGroup8.Size = new Size(314, 119);
            comparisonGroup8.TabIndex = 7;
            comparisonGroup8.TabStop = false;
            comparisonGroup8.Text = "8. مقایسه قیمت:";
            label8_8.AutoSize = true;
            label8_8.Location = new Point(75, 80);
            label8_8.Name = "label8_8";
            label8_8.Size = new Size(101, 25);
            label8_8.TabIndex = 0;
            label8_8.Text = "کندل گذشته";
            comparisonSecondTextBox8.Location = new Point(177, 76);
            comparisonSecondTextBox8.Name = "comparisonSecondTextBox8";
            comparisonSecondTextBox8.Size = new Size(57, 31);
            comparisonSecondTextBox8.TabIndex = 1;
            comparisonSecondTextBox8.Text = "5";
            comparisonSecondTextBox8.TextAlign = HorizontalAlignment.Center;
            label6_8.AutoSize = true;
            label6_8.Location = new Point(79, 45);
            label6_8.Name = "label6_8";
            label6_8.Size = new Size(101, 25);
            label6_8.TabIndex = 3;
            label6_8.Text = "کندل گذشته";
            comparisonFirstTextBox8.Location = new Point(177, 39);
            comparisonFirstTextBox8.Name = "comparisonFirstTextBox8";
            comparisonFirstTextBox8.Size = new Size(57, 31);
            comparisonFirstTextBox8.TabIndex = 4;
            comparisonFirstTextBox8.Text = "5";
            comparisonFirstTextBox8.TextAlign = HorizontalAlignment.Center;
            label5_8.AutoSize = true;
            label5_8.Location = new Point(319, 36);
            label5_8.Name = "label5_8";
            label5_8.Size = new Size(55, 25);
            label5_8.TabIndex = 5;
            label5_8.Text = "قیمت";
            comparisonFirstComboBox8.DropDownStyle = ComboBoxStyle.DropDownList;
            comparisonFirstComboBox8.Items.AddRange(new object[] { "O", "H", "L", "C", "V", "FINAL FEE" });
            comparisonFirstComboBox8.Location = new Point(236, 36);
            comparisonFirstComboBox8.Name = "comparisonFirstComboBox8";
            comparisonFirstComboBox8.Size = new Size(72, 33);
            comparisonFirstComboBox8.TabIndex = 6;
            comparisonOperatorComboBox8.DropDownStyle = ComboBoxStyle.DropDownList;
            comparisonOperatorComboBox8.Items.AddRange(new object[] { ">", "<", "=", ">=", "<=", "!=" });
            comparisonOperatorComboBox8.Location = new Point(3, 42);
            comparisonOperatorComboBox8.Name = "comparisonOperatorComboBox8";
            comparisonOperatorComboBox8.Size = new Size(73, 33);
            comparisonOperatorComboBox8.TabIndex = 7;
            comparisonSecondComboBox8.DropDownStyle = ComboBoxStyle.DropDownList;
            comparisonSecondComboBox8.Items.AddRange(new object[] { "O", "H", "L", "C", "V", "FINAL FEE" });
            comparisonSecondComboBox8.Location = new Point(236, 75);
            comparisonSecondComboBox8.Name = "comparisonSecondComboBox8";
            comparisonSecondComboBox8.Size = new Size(75, 33);
            comparisonSecondComboBox8.TabIndex = 8;
            comparisonGroup7.Controls.Add(label8_7);
            comparisonGroup7.Controls.Add(comparisonSecondTextBox7);
            comparisonGroup7.Controls.Add(label6_7);
            comparisonGroup7.Controls.Add(comparisonFirstTextBox7);
            comparisonGroup7.Controls.Add(label5_7);
            comparisonGroup7.Controls.Add(comparisonFirstComboBox7);
            comparisonGroup7.Controls.Add(comparisonOperatorComboBox7);
            comparisonGroup7.Controls.Add(comparisonSecondComboBox7);
            comparisonGroup7.Dock = DockStyle.Top;
            comparisonGroup7.Location = new Point(8, 638);
            comparisonGroup7.Name = "comparisonGroup7";
            comparisonGroup7.Size = new Size(314, 119);
            comparisonGroup7.TabIndex = 6;
            comparisonGroup7.TabStop = false;
            comparisonGroup7.Text = "7. مقایسه قیمت:";
            comparisonGroup6.Controls.Add(label8_6);
            comparisonGroup6.Controls.Add(comparisonSecondTextBox6);
            comparisonGroup6.Controls.Add(label6_6);
            comparisonGroup6.Controls.Add(comparisonFirstTextBox6);
            comparisonGroup6.Controls.Add(label5_6);
            comparisonGroup6.Controls.Add(comparisonFirstComboBox6);
            comparisonGroup6.Controls.Add(comparisonOperatorComboBox6);
            comparisonGroup6.Controls.Add(comparisonSecondComboBox6);
            comparisonGroup6.Dock = DockStyle.Top;
            comparisonGroup6.Location = new Point(8, 519);
            comparisonGroup6.Name = "comparisonGroup6";
            comparisonGroup6.Size = new Size(314, 119);
            comparisonGroup6.TabIndex = 5;
            comparisonGroup6.TabStop = false;
            comparisonGroup6.Text = "6. مقایسه قیمت:";
            comparisonGroup.Controls.Add(label8);
            comparisonGroup.Controls.Add(comparisonSecondTextBox);
            comparisonGroup.Controls.Add(label6);
            comparisonGroup.Controls.Add(comparisonFirstTextBox);
            comparisonGroup.Controls.Add(label5);
            comparisonGroup.Controls.Add(comparisonFirstComboBox);
            comparisonGroup.Controls.Add(comparisonOperatorComboBox);
            comparisonGroup.Controls.Add(comparisonSecondComboBox);
            comparisonGroup.Dock = DockStyle.Top;
            comparisonGroup.Location = new Point(8, 400);
            comparisonGroup.Name = "comparisonGroup";
            comparisonGroup.Size = new Size(314, 119);
            comparisonGroup.TabIndex = 4;
            comparisonGroup.TabStop = false;
            comparisonGroup.Text = "5. مقایسه قیمت:";
            pastDaysGroup.Controls.Add(label4);
            pastDaysGroup.Controls.Add(label3);
            pastDaysGroup.Controls.Add(pastDaysTextBox);
            pastDaysGroup.Controls.Add(pastDaysStatusComboBox);
            pastDaysGroup.Dock = DockStyle.Top;
            pastDaysGroup.Location = new Point(8, 281);
            pastDaysGroup.Name = "pastDaysGroup";
            pastDaysGroup.Size = new Size(314, 119);
            pastDaysGroup.TabIndex = 3;
            pastDaysGroup.TabStop = false;
            pastDaysGroup.Text = "4. روزهای گذشته:";
            volumeRatioGroup.Controls.Add(label2);
            volumeRatioGroup.Controls.Add(label1);
            volumeRatioGroup.Controls.Add(textBox1);
            volumeRatioGroup.Controls.Add(volumeRatioTextBox);
            volumeRatioGroup.Controls.Add(volumeRatioOperatorComboBox);
            volumeRatioGroup.Dock = DockStyle.Top;
            volumeRatioGroup.Location = new Point(8, 196);
            volumeRatioGroup.Name = "volumeRatioGroup";
            volumeRatioGroup.Size = new Size(314, 85);
            volumeRatioGroup.TabIndex = 2;
            volumeRatioGroup.TabStop = false;
            volumeRatioGroup.Text = "3. نسبت حجم:";
            nameFilterGroup.Controls.Add(nameComboBox);
            nameFilterGroup.Controls.Add(nameTextBox);
            nameFilterGroup.Dock = DockStyle.Top;
            nameFilterGroup.Location = new Point(8, 111);
            nameFilterGroup.Name = "nameFilterGroup";
            nameFilterGroup.Size = new Size(314, 85);
            nameFilterGroup.TabIndex = 1;
            nameFilterGroup.TabStop = false;
            nameFilterGroup.Text = "2. نام نماد:";
            tradingStatusGroup.Controls.Add(statusAllRadio);
            tradingStatusGroup.Controls.Add(statusPositiveRadio);
            tradingStatusGroup.Controls.Add(statusNegativeRadio);
            tradingStatusGroup.Dock = DockStyle.Top;
            tradingStatusGroup.Location = new Point(8, 8);
            tradingStatusGroup.Name = "tradingStatusGroup";
            tradingStatusGroup.Size = new Size(314, 103);
            tradingStatusGroup.TabIndex = 0;
            tradingStatusGroup.TabStop = false;
            tradingStatusGroup.Text = "1. وضعیت معامله امروز:";
            tabPage3.Location = new Point(4, 34);
            tabPage3.Name = "tabPage3";
            tabPage3.Padding = new Padding(8);
            tabPage3.Size = new Size(360, 787);
            tabPage3.TabIndex = 2;
            tabPage3.Text = "شناسه";
            identifierMainGroup.Dock = DockStyle.Top;
            identifierMainGroup.Location = new Point(8, 8);
            identifierMainGroup.Name = "identifierMainGroup";
            identifierMainGroup.Size = new Size(344, 620);
            identifierMainGroup.TabIndex = 0;
            identifierMainGroup.TabStop = false;
            identifierMainGroup.Text = "اطلاعات شناسه";
            identifierMainGroup.Controls.Add(identifierLayout);
            identifierLayout.Dock = DockStyle.Fill;
            identifierLayout.ColumnCount = 2;
            identifierLayout.RowCount = 6;
            identifierLayout.Location = new Point(3, 27);
            identifierLayout.Name = "identifierLayout";
            identifierLayout.Size = new Size(338, 590);
            identifierLayout.TabIndex = 0;
            marketsTabPage.Location = new Point(4, 34);
            marketsTabPage.Name = "marketsTabPage";
            marketsTabPage.Padding = new Padding(8);
            marketsTabPage.Size = new Size(360, 787);
            marketsTabPage.TabIndex = 3;
            marketsTabPage.Text = "بازارها";
            Controls.Add(mainSplitContainer);
            Controls.Add(mainMenuStrip);
            MainMenuStrip = mainMenuStrip;
            Name = "MainForm";
            RightToLeft = RightToLeft.Yes;
            RightToLeftLayout = true;
            Text = "Trade.It";
            WindowState = FormWindowState.Maximized;
            mainMenuStrip.ResumeLayout(false);
            mainMenuStrip.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)mainSplitContainer).EndInit();
            mainSplitContainer.Panel1.ResumeLayout(false);
            mainSplitContainer.Panel2.ResumeLayout(false);
            mainSplitContainer.ResumeLayout(false);
            chartPanel.ResumeLayout(false);
            chartTabControl.ResumeLayout(false);
            chartTabPage.ResumeLayout(false);
            chartInfoPanel.ResumeLayout(false);
            chartToolbarPanel.ResumeLayout(false);
            controlTabControl.ResumeLayout(false);
            stocksTabPage.ResumeLayout(false);
            groupBox1.ResumeLayout(false);
            groupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)stocksDataGridView).EndInit();
            tabPage2.ResumeLayout(false);
            ohlcChangeFilterGroup.ResumeLayout(false);
            ohlcChangeFilterGroup.PerformLayout();
            comparisonGroup8.ResumeLayout(false);
            comparisonGroup8.PerformLayout();
            comparisonGroup7.ResumeLayout(false);
            comparisonGroup7.PerformLayout();
            comparisonGroup6.ResumeLayout(false);
            comparisonGroup6.PerformLayout();
            comparisonGroup.ResumeLayout(false);
            comparisonGroup.PerformLayout();
            pastDaysGroup.ResumeLayout(false);
            pastDaysGroup.PerformLayout();
            volumeRatioGroup.ResumeLayout(false);
            volumeRatioGroup.PerformLayout();
            nameFilterGroup.ResumeLayout(false);
            nameFilterGroup.PerformLayout();
            tradingStatusGroup.ResumeLayout(false);
            tradingStatusGroup.PerformLayout();
            tabPage3.ResumeLayout(false);
            identifierMainGroup.ResumeLayout(false);
            identifierLayout.ResumeLayout(false);
            marketsTabPage.ResumeLayout(false);
            ResumeLayout(false);
            PerformLayout();
        }

        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
    }
}