namespace Trade.It
{
    partial class PortfolioManagementForm
    {
        private System.ComponentModel.IContainer components = null;

        private Label titleLabel;
        private Button reloadButton;
        private Label parametersTitleLabel;
        private Label portfolioNameCaption;
        private Label portfolioNameLabel;
        private Label sourceTypeCaption;
        private Label sourceTypeLabel;
        private Label dataPathCaption;
        private Label dataPathLabel;
        private Label dataTypeCaption;
        private Label dataTypeLabel;
        private Label symbolSourceCaption;
        private Label symbolSourceLabel;
        private Label separatorCaption;
        private Label separatorLabel;
        private Label timeFormatCaption;
        private Label timeFormatLabel;
        private Label dateFormatCaption;
        private Label dateFormatLabel;
        private Label headerCaption;
        private Label headerLabel;
        private Label calendarCaption;
        private Label calendarLabel;
        private Label symbolCountCaption;
        private Label symbolCountLabel;
        private Label existingTitleLabel;
        private ListBox portfoliosListBox;
        private Button deletePortfoliosButton;
        private Label symbolsTitleLabel;
        private DataGridView symbolsGrid;
        private Button deleteSymbolsButton;
        private Label statusLabel;
        private Button closeButton;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            titleLabel = new Label();
            reloadButton = new Button();
            parametersTitleLabel = new Label();
            portfolioNameCaption = new Label();
            portfolioNameLabel = new Label();
            sourceTypeCaption = new Label();
            sourceTypeLabel = new Label();
            dataPathCaption = new Label();
            dataPathLabel = new Label();
            dataTypeCaption = new Label();
            dataTypeLabel = new Label();
            symbolSourceCaption = new Label();
            symbolSourceLabel = new Label();
            separatorCaption = new Label();
            separatorLabel = new Label();
            timeFormatCaption = new Label();
            timeFormatLabel = new Label();
            dateFormatCaption = new Label();
            dateFormatLabel = new Label();
            headerCaption = new Label();
            headerLabel = new Label();
            calendarCaption = new Label();
            calendarLabel = new Label();
            symbolCountCaption = new Label();
            symbolCountLabel = new Label();
            existingTitleLabel = new Label();
            portfoliosListBox = new ListBox();
            deletePortfoliosButton = new Button();
            symbolsTitleLabel = new Label();
            symbolsGrid = new DataGridView();
            deleteSymbolsButton = new Button();
            statusLabel = new Label();
            closeButton = new Button();
            ((System.ComponentModel.ISupportInitialize)symbolsGrid).BeginInit();
            SuspendLayout();
            // Form
            Text = "مدیریت سبدها";
            StartPosition = FormStartPosition.CenterParent;
            RightToLeft = RightToLeft.Yes;
            RightToLeftLayout = true;
            MinimumSize = new Size(1100, 700);
            ClientSize = new Size(1400, 820);
            Font = new Font("Segoe UI", 10F);
            // Header
            titleLabel.Text = "مدیریت سبدها";
            titleLabel.Location = new Point(250, 18);
            titleLabel.Size = new Size(1120, 40);
            titleLabel.Name = "titleLabel";
            titleLabel.TextAlign = ContentAlignment.MiddleRight;
            titleLabel.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            reloadButton.Text = "بازخوانی";
            reloadButton.Location = new Point(20, 21);
            reloadButton.Size = new Size(110, 34);
            reloadButton.Name = "reloadButton";
            // Parameters section - direct controls, no layout container
            parametersTitleLabel.Text = "پارامترهای سبد";
            parametersTitleLabel.Location = new Point(20, 70);
            parametersTitleLabel.Size = new Size(1350, 34);
            parametersTitleLabel.Name = "parametersTitleLabel";
            parametersTitleLabel.TextAlign = ContentAlignment.MiddleRight;
            parametersTitleLabel.Font = new Font("Segoe UI", 11F, FontStyle.Bold);

            portfolioNameCaption.Text = "نام سبد:";
            portfolioNameCaption.Location = new Point(1030, 110);
            portfolioNameCaption.Size = new Size(100, 34);
            portfolioNameCaption.Name = "portfolioNameCaption";
            portfolioNameCaption.TextAlign = ContentAlignment.MiddleRight;
            portfolioNameLabel.Text = "—";
            portfolioNameLabel.Location = new Point(720, 110);
            portfolioNameLabel.Size = new Size(300, 34);
            portfolioNameLabel.Name = "portfolioNameLabel";
            portfolioNameLabel.TextAlign = ContentAlignment.MiddleRight;
            portfolioNameLabel.BorderStyle = BorderStyle.FixedSingle;

            sourceTypeCaption.Text = "نوع منبع:";
            sourceTypeCaption.Location = new Point(610, 110);
            sourceTypeCaption.Size = new Size(100, 34);
            sourceTypeCaption.Name = "sourceTypeCaption";
            sourceTypeCaption.TextAlign = ContentAlignment.MiddleRight;
            sourceTypeLabel.Text = "—";
            sourceTypeLabel.Location = new Point(300, 110);
            sourceTypeLabel.Size = new Size(300, 34);
            sourceTypeLabel.Name = "sourceTypeLabel";
            sourceTypeLabel.TextAlign = ContentAlignment.MiddleRight;
            sourceTypeLabel.BorderStyle = BorderStyle.FixedSingle;

            dataPathCaption.Text = "مسیر داده:";
            dataPathCaption.Location = new Point(1030, 150);
            dataPathCaption.Size = new Size(100, 34);
            dataPathCaption.Name = "dataPathCaption";
            dataPathCaption.TextAlign = ContentAlignment.MiddleRight;
            dataPathLabel.Text = "—";
            dataPathLabel.Location = new Point(720, 150);
            dataPathLabel.Size = new Size(300, 34);
            dataPathLabel.Name = "dataPathLabel";
            dataPathLabel.TextAlign = ContentAlignment.MiddleRight;
            dataPathLabel.BorderStyle = BorderStyle.FixedSingle;
            dataPathLabel.AutoEllipsis = true;
            dataTypeCaption.Text = "نوع داده:";
            dataTypeCaption.Location = new Point(610, 150);
            dataTypeCaption.Size = new Size(100, 34);
            dataTypeCaption.Name = "dataTypeCaption";
            dataTypeCaption.TextAlign = ContentAlignment.MiddleRight;
            dataTypeLabel.Text = "—";
            dataTypeLabel.Location = new Point(300, 150);
            dataTypeLabel.Size = new Size(300, 34);
            dataTypeLabel.Name = "dataTypeLabel";
            dataTypeLabel.TextAlign = ContentAlignment.MiddleRight;
            dataTypeLabel.BorderStyle = BorderStyle.FixedSingle;

            symbolSourceCaption.Text = "منبع نام نماد:";
            symbolSourceCaption.Location = new Point(1030, 190);
            symbolSourceCaption.Size = new Size(100, 34);
            symbolSourceCaption.Name = "symbolSourceCaption";
            symbolSourceCaption.TextAlign = ContentAlignment.MiddleRight;
            symbolSourceLabel.Text = "—";
            symbolSourceLabel.Location = new Point(720, 190);
            symbolSourceLabel.Size = new Size(300, 34);
            symbolSourceLabel.Name = "symbolSourceLabel";
            symbolSourceLabel.TextAlign = ContentAlignment.MiddleRight;
            symbolSourceLabel.BorderStyle = BorderStyle.FixedSingle;
            separatorCaption.Text = "جداکننده:";
            separatorCaption.Location = new Point(610, 190);
            separatorCaption.Size = new Size(100, 34);
            separatorCaption.Name = "separatorCaption";
            separatorCaption.TextAlign = ContentAlignment.MiddleRight;
            separatorLabel.Text = "—";
            separatorLabel.Location = new Point(300, 190);
            separatorLabel.Size = new Size(300, 34);
            separatorLabel.Name = "separatorLabel";
            separatorLabel.TextAlign = ContentAlignment.MiddleRight;
            separatorLabel.BorderStyle = BorderStyle.FixedSingle;

            timeFormatCaption.Text = "فرمت زمان:";
            timeFormatCaption.Location = new Point(1030, 230);
            timeFormatCaption.Size = new Size(100, 34);
            timeFormatCaption.Name = "timeFormatCaption";
            timeFormatCaption.TextAlign = ContentAlignment.MiddleRight;
            timeFormatLabel.Text = "—";
            timeFormatLabel.Location = new Point(720, 230);
            timeFormatLabel.Size = new Size(300, 34);
            timeFormatLabel.Name = "timeFormatLabel";
            timeFormatLabel.TextAlign = ContentAlignment.MiddleRight;
            timeFormatLabel.BorderStyle = BorderStyle.FixedSingle;
            dateFormatCaption.Text = "فرمت تاریخ:";
            dateFormatCaption.Location = new Point(610, 230);
            dateFormatCaption.Size = new Size(100, 34);
            dateFormatCaption.Name = "dateFormatCaption";
            dateFormatCaption.TextAlign = ContentAlignment.MiddleRight;
            dateFormatLabel.Text = "—";
            dateFormatLabel.Location = new Point(300, 230);
            dateFormatLabel.Size = new Size(300, 34);
            dateFormatLabel.Name = "dateFormatLabel";
            dateFormatLabel.TextAlign = ContentAlignment.MiddleRight;
            dateFormatLabel.BorderStyle = BorderStyle.FixedSingle;

            headerCaption.Text = "Header:";
            headerCaption.Location = new Point(1030, 270);
            headerCaption.Size = new Size(100, 34);
            headerCaption.Name = "headerCaption";
            headerCaption.TextAlign = ContentAlignment.MiddleRight;
            headerLabel.Text = "—";
            headerLabel.Location = new Point(720, 270);
            headerLabel.Size = new Size(300, 34);
            headerLabel.Name = "headerLabel";
            headerLabel.TextAlign = ContentAlignment.MiddleRight;
            headerLabel.BorderStyle = BorderStyle.FixedSingle;
            calendarCaption.Text = "تقویم:";
            calendarCaption.Location = new Point(610, 270);
            calendarCaption.Size = new Size(100, 34);
            calendarCaption.Name = "calendarCaption";
            calendarCaption.TextAlign = ContentAlignment.MiddleRight;
            calendarLabel.Text = "—";
            calendarLabel.Location = new Point(300, 270);
            calendarLabel.Size = new Size(300, 34);
            calendarLabel.Name = "calendarLabel";
            calendarLabel.TextAlign = ContentAlignment.MiddleRight;
            calendarLabel.BorderStyle = BorderStyle.FixedSingle;
            symbolCountCaption.Text = "تعداد نماد:";
            symbolCountCaption.Location = new Point(1030, 310);
            symbolCountCaption.Size = new Size(100, 34);
            symbolCountCaption.Name = "symbolCountCaption";
            symbolCountCaption.TextAlign = ContentAlignment.MiddleRight;
            symbolCountLabel.Text = "۰";
            symbolCountLabel.Location = new Point(720, 310);
            symbolCountLabel.Size = new Size(300, 34);
            symbolCountLabel.Name = "symbolCountLabel";
            symbolCountLabel.TextAlign = ContentAlignment.MiddleRight;
            symbolCountLabel.BorderStyle = BorderStyle.FixedSingle;
            // Existing portfolios
            existingTitleLabel.Text = "سبدهای موجود";
            existingTitleLabel.Location = new Point(960, 365);
            existingTitleLabel.Size = new Size(410, 34);
            existingTitleLabel.Name = "existingTitleLabel";
            existingTitleLabel.TextAlign = ContentAlignment.MiddleRight;
            existingTitleLabel.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            portfoliosListBox.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Right;
            portfoliosListBox.IntegralHeight = false;
            portfoliosListBox.Location = new Point(960, 402);
            portfoliosListBox.Size = new Size(410, 280);
            portfoliosListBox.Name = "portfoliosListBox";
            deletePortfoliosButton.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            deletePortfoliosButton.Text = "حذف سبد انتخاب شده";
            deletePortfoliosButton.Location = new Point(960, 690);
            deletePortfoliosButton.Size = new Size(410, 40);
            deletePortfoliosButton.Name = "deletePortfoliosButton";
            // Symbols
            symbolsTitleLabel.Text = "نمادهای سبد";
            symbolsTitleLabel.Location = new Point(20, 365);
            symbolsTitleLabel.Size = new Size(910, 34);
            symbolsTitleLabel.Name = "symbolsTitleLabel";
            symbolsTitleLabel.TextAlign = ContentAlignment.MiddleRight;
            symbolsTitleLabel.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            symbolsGrid.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left;
            symbolsGrid.AllowUserToAddRows = false;
            symbolsGrid.AllowUserToDeleteRows = false;
            symbolsGrid.ReadOnly = true;
            symbolsGrid.AutoGenerateColumns = false;
            symbolsGrid.RowHeadersVisible = false;
            symbolsGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            symbolsGrid.MultiSelect = true;
            symbolsGrid.RightToLeft = RightToLeft.Yes;
            symbolsGrid.BackgroundColor = SystemColors.Window;
            symbolsGrid.BorderStyle = BorderStyle.FixedSingle;
            symbolsGrid.Location = new Point(20, 402);
            symbolsGrid.Size = new Size(910, 280);
            symbolsGrid.Name = "symbolsGrid";
            symbolsGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "rowColumn", HeaderText = "ردیف", Width = 70 });
            symbolsGrid.Columns.Add(new DataGridViewCheckBoxColumn { Name = "selectedColumn", HeaderText = "انتخاب", Width = 80 });
            symbolsGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "symbolColumn", HeaderText = "نماد", Width = 140 });
            symbolsGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "displayNameColumn", HeaderText = "نام نمایشی", Width = 190 });
            symbolsGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "lastTradeColumn", HeaderText = "آخرین معامله", Width = 150 });
            symbolsGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "volumeColumn", HeaderText = "حجم", Width = 130 });
            symbolsGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "closeColumn", HeaderText = "قیمت پایانی", AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill });
            deleteSymbolsButton.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            deleteSymbolsButton.Text = "حذف نمادهای انتخاب شده";
            deleteSymbolsButton.Location = new Point(20, 690);
            deleteSymbolsButton.Size = new Size(910, 40);
            deleteSymbolsButton.Name = "deleteSymbolsButton";
            // Footer
            statusLabel.Text = "هیچ سبدی انتخاب نشده است.";
            statusLabel.Anchor = AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            statusLabel.Location = new Point(20, 745);
            statusLabel.Size = new Size(1250, 34);
            statusLabel.Name = "statusLabel";
            statusLabel.TextAlign = ContentAlignment.MiddleRight;
            closeButton.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            closeButton.Text = "بستن";
            closeButton.Location = new Point(1270, 745);
            closeButton.Size = new Size(100, 34);
            closeButton.Name = "closeButton";
            // Direct form children
            Controls.Add(titleLabel);
            Controls.Add(reloadButton);
            Controls.Add(parametersTitleLabel);
            Controls.Add(portfolioNameCaption);
            Controls.Add(portfolioNameLabel);
            Controls.Add(sourceTypeCaption);
            Controls.Add(sourceTypeLabel);
            Controls.Add(dataPathCaption);
            Controls.Add(dataPathLabel);
            Controls.Add(dataTypeCaption);
            Controls.Add(dataTypeLabel);
            Controls.Add(symbolSourceCaption);
            Controls.Add(symbolSourceLabel);
            Controls.Add(separatorCaption);
            Controls.Add(separatorLabel);
            Controls.Add(timeFormatCaption);
            Controls.Add(timeFormatLabel);
            Controls.Add(dateFormatCaption);
            Controls.Add(dateFormatLabel);
            Controls.Add(headerCaption);
            Controls.Add(headerLabel);
            Controls.Add(calendarCaption);
            Controls.Add(calendarLabel);
            Controls.Add(symbolCountCaption);
            Controls.Add(symbolCountLabel);
            Controls.Add(existingTitleLabel);
            Controls.Add(portfoliosListBox);
            Controls.Add(deletePortfoliosButton);
            Controls.Add(symbolsTitleLabel);
            Controls.Add(symbolsGrid);
            Controls.Add(deleteSymbolsButton);
            Controls.Add(statusLabel);
            Controls.Add(closeButton);
            ((System.ComponentModel.ISupportInitialize)symbolsGrid).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }
    }
}