namespace Trade.It
{
    partial class PortfolioDefinitionForm
    {
        private System.ComponentModel.IContainer components = null;
        private TableLayoutPanel mainTable;
        private TableLayoutPanel nameTable;
        private Label portfolioNameLabel;
        private TextBox portfolioNameTextBox;
        private GroupBox sourceGroup;
        private RadioButton fileNameRadioButton;
        private RadioButton insideFileRadioButton;
        private TableLayoutPanel pathTable;
        private Label dataPathLabel;
        private TextBox dataPathTextBox;
        private Button browseButton;
        private TableLayoutPanel optionsTable;
        private Label separatorLabel;
        private ComboBox separatorComboBox;
        private Label calendarLabel;
        private ComboBox calendarComboBox;
        private Label timeFormatLabel;
        private ComboBox timeFormatComboBox;
        private Label dateFormatLabel;
        private ComboBox dateFormatComboBox;
        private CheckBox headerCheckBox;
        private CheckBox noDateTimeCheckBox;
        private TableLayoutPanel middleTable;
        private GroupBox mappingGroup;
        private DataGridView mappingGrid;
        private GroupBox symbolSelectionGroup;
        private TableLayoutPanel symbolTable;
        private TextBox symbolSearchTextBox;
        private Button selectAllButton;
        private Button deselectAllButton;
        private Label selectedCountLabel;
        private DataGridView symbolGrid;
        private GroupBox previewGroup;
        private DataGridView previewGrid;
        private Panel buttonPanel;
        private Button testMappingButton;
        private Button saveButton;
        private Button cancelButton;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            mainTable = new TableLayoutPanel();
            nameTable = new TableLayoutPanel();
            portfolioNameLabel = new Label();
            portfolioNameTextBox = new TextBox();
            sourceGroup = new GroupBox();
            fileNameRadioButton = new RadioButton();
            insideFileRadioButton = new RadioButton();
            pathTable = new TableLayoutPanel();
            dataPathLabel = new Label();
            dataPathTextBox = new TextBox();
            browseButton = new Button();
            optionsTable = new TableLayoutPanel();
            separatorLabel = new Label();
            separatorComboBox = new ComboBox();
            calendarLabel = new Label();
            calendarComboBox = new ComboBox();
            timeFormatLabel = new Label();
            timeFormatComboBox = new ComboBox();
            dateFormatLabel = new Label();
            dateFormatComboBox = new ComboBox();
            headerCheckBox = new CheckBox();
            noDateTimeCheckBox = new CheckBox();
            middleTable = new TableLayoutPanel();
            mappingGroup = new GroupBox();
            mappingGrid = new DataGridView();
            symbolSelectionGroup = new GroupBox();
            symbolTable = new TableLayoutPanel();
            symbolSearchTextBox = new TextBox();
            selectAllButton = new Button();
            deselectAllButton = new Button();
            selectedCountLabel = new Label();
            symbolGrid = new DataGridView();
            previewGroup = new GroupBox();
            previewGrid = new DataGridView();
            buttonPanel = new Panel();
            testMappingButton = new Button();
            saveButton = new Button();
            cancelButton = new Button();
            SuspendLayout();

            Text = "تعریف سبد";
            StartPosition = FormStartPosition.CenterParent;
            RightToLeft = RightToLeft.Yes;
            RightToLeftLayout = true;
            MinimumSize = new Size(1200, 760);
            ClientSize = new Size(1500, 900);
            Font = new Font("Segoe UI", 10F);

            mainTable.Dock = DockStyle.Fill;
            mainTable.Padding = new Padding(12, 12, 12, 64);
            mainTable.ColumnCount = 1;
            mainTable.RowCount = 6;
            mainTable.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            mainTable.RowStyles.Add(new RowStyle(SizeType.Absolute, 46F));
            mainTable.RowStyles.Add(new RowStyle(SizeType.Absolute, 68F));
            mainTable.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
            mainTable.RowStyles.Add(new RowStyle(SizeType.Absolute, 58F));
            mainTable.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            mainTable.RowStyles.Add(new RowStyle(SizeType.Absolute, 145F));

            nameTable.Dock = DockStyle.Fill;
            nameTable.ColumnCount = 2;
            nameTable.RowCount = 1;
            nameTable.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 100F));
            nameTable.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            portfolioNameLabel.Text = "نام سبد:";
            portfolioNameLabel.Dock = DockStyle.Fill;
            portfolioNameLabel.TextAlign = ContentAlignment.MiddleRight;
            portfolioNameTextBox.Dock = DockStyle.Fill;
            portfolioNameTextBox.Margin = new Padding(4);
            nameTable.Controls.Add(portfolioNameLabel, 0, 0);
            nameTable.Controls.Add(portfolioNameTextBox, 1, 0);
            mainTable.Controls.Add(nameTable, 0, 0);

            sourceGroup.Text = "منبع اطلاعات";
            sourceGroup.Dock = DockStyle.Fill;
            sourceGroup.Padding = new Padding(12, 8, 12, 8);
            fileNameRadioButton.Text = "نام فایل";
            fileNameRadioButton.AutoSize = true;
            fileNameRadioButton.Checked = true;
            fileNameRadioButton.Location = new Point(820, 27);
            insideFileRadioButton.Text = "داخل فایل";
            insideFileRadioButton.AutoSize = true;
            insideFileRadioButton.Location = new Point(680, 27);
            sourceGroup.Controls.Add(fileNameRadioButton);
            sourceGroup.Controls.Add(insideFileRadioButton);
            mainTable.Controls.Add(sourceGroup, 0, 1);

            pathTable.Dock = DockStyle.Fill;
            pathTable.ColumnCount = 3;
            pathTable.RowCount = 1;
            pathTable.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 100F));
            pathTable.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            pathTable.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140F));
            dataPathLabel.Text = "مسیر داده:";
            dataPathLabel.Dock = DockStyle.Fill;
            dataPathLabel.TextAlign = ContentAlignment.MiddleRight;
            dataPathTextBox.Dock = DockStyle.Fill;
            dataPathTextBox.Margin = new Padding(4);
            browseButton.Text = "انتخاب پوشه...";
            browseButton.Dock = DockStyle.Fill;
            browseButton.Margin = new Padding(4);
            pathTable.Controls.Add(dataPathLabel, 0, 0);
            pathTable.Controls.Add(dataPathTextBox, 1, 0);
            pathTable.Controls.Add(browseButton, 2, 0);
            mainTable.Controls.Add(pathTable, 0, 2);

            optionsTable.Dock = DockStyle.Fill;
            optionsTable.ColumnCount = 10;
            optionsTable.RowCount = 1;
            optionsTable.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 70F));
            optionsTable.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 145F));
            optionsTable.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 55F));
            optionsTable.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 145F));
            optionsTable.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 78F));
            optionsTable.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 135F));
            optionsTable.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 78F));
            optionsTable.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 135F));
            optionsTable.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 170F));
            optionsTable.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            separatorLabel.Text = "جداکننده:";
            separatorLabel.Dock = DockStyle.Fill;
            separatorLabel.TextAlign = ContentAlignment.MiddleRight;
            separatorComboBox.Dock = DockStyle.Fill;
            separatorComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            separatorComboBox.Items.AddRange(new object[] { "Comma (,)", "Semicolon (;)", "Tab", "Pipe (|)" });
            separatorComboBox.SelectedIndex = 0;
            calendarLabel.Text = "تقویم:";
            calendarLabel.Dock = DockStyle.Fill;
            calendarLabel.TextAlign = ContentAlignment.MiddleRight;
            calendarComboBox.Dock = DockStyle.Fill;
            calendarComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            calendarComboBox.Items.AddRange(new object[] { "شمسی (Persian)", "لاتین (Gregorian)" });
            calendarComboBox.SelectedIndex = 0;
            timeFormatLabel.Text = "زمان:";
            timeFormatLabel.Dock = DockStyle.Fill;
            timeFormatLabel.TextAlign = ContentAlignment.MiddleRight;
            timeFormatComboBox.Dock = DockStyle.Fill;
            timeFormatComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            timeFormatComboBox.Items.AddRange(new object[] { "HHMMSS", "HH:MM:SS", "HHMM" });
            timeFormatComboBox.SelectedIndex = 0;
            dateFormatLabel.Text = "تاریخ:";
            dateFormatLabel.Dock = DockStyle.Fill;
            dateFormatLabel.TextAlign = ContentAlignment.MiddleRight;
            dateFormatComboBox.Dock = DockStyle.Fill;
            dateFormatComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            dateFormatComboBox.Items.AddRange(new object[] { "YYYYMMDD", "YYYY-MM-DD", "YYYY/MM/DD" });
            dateFormatComboBox.SelectedIndex = 0;
            headerCheckBox.Text = "سطر اول عنوان ستون‌ها";
            headerCheckBox.Dock = DockStyle.Fill;
            noDateTimeCheckBox.Text = "فاقد تاریخ/زمان";
            noDateTimeCheckBox.Dock = DockStyle.Fill;
            optionsTable.Controls.Add(separatorLabel, 0, 0);
            optionsTable.Controls.Add(separatorComboBox, 1, 0);
            optionsTable.Controls.Add(calendarLabel, 2, 0);
            optionsTable.Controls.Add(calendarComboBox, 3, 0);
            optionsTable.Controls.Add(timeFormatLabel, 4, 0);
            optionsTable.Controls.Add(timeFormatComboBox, 5, 0);
            optionsTable.Controls.Add(dateFormatLabel, 6, 0);
            optionsTable.Controls.Add(dateFormatComboBox, 7, 0);
            optionsTable.Controls.Add(headerCheckBox, 8, 0);
            optionsTable.Controls.Add(noDateTimeCheckBox, 9, 0);
            mainTable.Controls.Add(optionsTable, 0, 3);

            middleTable.Dock = DockStyle.Fill;
            middleTable.ColumnCount = 2;
            middleTable.RowCount = 1;
            middleTable.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 40F));
            middleTable.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 60F));

            mappingGroup.Text = "Mapping ستون‌های فایل";
            mappingGroup.Dock = DockStyle.Fill;
            mappingGroup.Padding = new Padding(8);
            mappingGrid.Dock = DockStyle.Fill;
            mappingGrid.AllowUserToAddRows = false;
            mappingGrid.AllowUserToDeleteRows = false;
            mappingGrid.AutoGenerateColumns = false;
            mappingGrid.RowHeadersVisible = false;
            mappingGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            mappingGrid.RightToLeft = RightToLeft.Yes;
            mappingGrid.BackgroundColor = SystemColors.Window;
            mappingGrid.BorderStyle = BorderStyle.FixedSingle;
            mappingGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "standardField", HeaderText = "فیلد استاندارد", ReadOnly = true, Width = 165 });
            mappingGrid.Columns.Add(new DataGridViewComboBoxColumn { Name = "fileColumn", HeaderText = "ستون فایل", Width = 185 });
            mappingGrid.Rows.Add("نماد", "");
            mappingGrid.Rows.Add("تاریخ", "");
            mappingGrid.Rows.Add("زمان", "");
            mappingGrid.Rows.Add("Open", "");
            mappingGrid.Rows.Add("High", "");
            mappingGrid.Rows.Add("Low", "");
            mappingGrid.Rows.Add("Close", "");
            mappingGrid.Rows.Add("حجم", "");
            mappingGrid.Rows.Add("قیمت پایانی امروز", "");
            mappingGrid.Rows.Add("قیمت پایانی دیروز", "");
            mappingGrid.Rows.Add("تعداد معامله", "");
            mappingGrid.Rows.Add("ارزش معاملات", "");
            mappingGrid.Rows.Add("تعداد سهم", "");
            mappingGrid.Rows.Add("ارزش بازار", "");
            mappingGrid.Rows.Add("نماد انگلیسی", "");
            mappingGroup.Controls.Add(mappingGrid);
            middleTable.Controls.Add(mappingGroup, 0, 0);

            symbolSelectionGroup.Text = "انتخاب سهام";
            symbolSelectionGroup.Dock = DockStyle.Fill;
            symbolSelectionGroup.Padding = new Padding(8);
            symbolTable.Dock = DockStyle.Fill;
            symbolTable.ColumnCount = 4;
            symbolTable.RowCount = 2;
            symbolTable.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 105F));
            symbolTable.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 125F));
            symbolTable.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            symbolTable.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 180F));
            symbolTable.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
            symbolTable.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            selectAllButton.Text = "انتخاب همه";
            selectAllButton.Dock = DockStyle.Fill;
            selectAllButton.Margin = new Padding(3);
            deselectAllButton.Text = "عدم انتخاب همه";
            deselectAllButton.Dock = DockStyle.Fill;
            deselectAllButton.Margin = new Padding(3);
            symbolSearchTextBox.PlaceholderText = "جستجوی نماد...";
            symbolSearchTextBox.Dock = DockStyle.Fill;
            symbolSearchTextBox.Margin = new Padding(3);
            selectedCountLabel.Text = "انتخاب شده: ۰ از ۰";
            selectedCountLabel.Dock = DockStyle.Fill;
            selectedCountLabel.TextAlign = ContentAlignment.MiddleRight;
            symbolTable.Controls.Add(selectAllButton, 0, 0);
            symbolTable.Controls.Add(deselectAllButton, 1, 0);
            symbolTable.Controls.Add(symbolSearchTextBox, 2, 0);
            symbolTable.Controls.Add(selectedCountLabel, 3, 0);
            symbolGrid.Dock = DockStyle.Fill;
            symbolGrid.AllowUserToAddRows = false;
            symbolGrid.AllowUserToDeleteRows = false;
            symbolGrid.AutoGenerateColumns = false;
            symbolGrid.RowHeadersVisible = false;
            symbolGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            symbolGrid.RightToLeft = RightToLeft.Yes;
            symbolGrid.BackgroundColor = SystemColors.Window;
            symbolGrid.BorderStyle = BorderStyle.FixedSingle;
            symbolGrid.Columns.Add(new DataGridViewCheckBoxColumn { Name = "selectedColumn", HeaderText = "انتخاب", Width = 75 });
            symbolGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "symbolColumn", HeaderText = "نماد", AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill, ReadOnly = true });
            symbolTable.Controls.Add(symbolGrid, 0, 1);
            symbolTable.SetColumnSpan(symbolGrid, 4);
            symbolSelectionGroup.Controls.Add(symbolTable);
            middleTable.Controls.Add(symbolSelectionGroup, 1, 0);
            mainTable.Controls.Add(middleTable, 0, 4);

            previewGroup.Text = "پیش‌نمایش داده";
            previewGroup.Dock = DockStyle.Fill;
            previewGroup.Padding = new Padding(8);
            previewGrid.Dock = DockStyle.Fill;
            previewGrid.AllowUserToAddRows = false;
            previewGrid.AllowUserToDeleteRows = false;
            previewGrid.ReadOnly = true;
            previewGrid.AutoGenerateColumns = false;
            previewGrid.RowHeadersVisible = false;
            previewGrid.RightToLeft = RightToLeft.Yes;
            previewGrid.BackgroundColor = SystemColors.Window;
            previewGrid.BorderStyle = BorderStyle.FixedSingle;
            previewGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "previewSymbol", HeaderText = "نماد", Width = 120 });
            previewGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "previewFile", HeaderText = "نام فایل", Width = 220 });
            previewGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "previewColumns", HeaderText = "ستون‌های موجود در فایل", AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill });
            previewGroup.Controls.Add(previewGrid);
            mainTable.Controls.Add(previewGroup, 0, 5);

            buttonPanel.Dock = DockStyle.Bottom;
            buttonPanel.Height = 52;
            testMappingButton.Text = "تست Mapping";
            testMappingButton.Size = new Size(135, 36);
            testMappingButton.Location = new Point(12, 8);
            cancelButton.Text = "لغو";
            cancelButton.Size = new Size(90, 36);
            cancelButton.Location = new Point(152, 8);
            saveButton.Text = "ذخیره سبد";
            saveButton.Size = new Size(125, 36);
            saveButton.Location = new Point(247, 8);
            buttonPanel.Controls.Add(testMappingButton);
            buttonPanel.Controls.Add(cancelButton);
            buttonPanel.Controls.Add(saveButton);

            Controls.Add(mainTable);
            Controls.Add(buttonPanel);
            ResumeLayout(false);
            PerformLayout();
        }
    }
}
